/*********************************************************************
SYBREX SYSTEMS INCORPORATED
Copyright (C) 2003-2005 Sybrex Systems Incorporated
All rights reserved.

NOTICE: Sybrex permits you to use, modify, and distribute this file
in accordance with the terms of the Sybrex license agreement
accompanying it. If you have received this file from a source other
than Sybrex, then your use, modification, or distribution of it
requires the prior written permission of Sybrex.

---------------------------------------------------------------------
VSTypes.h
*********************************************************************/
/*********************************************************************
*********************************************************************/


#ifndef tiffredef_H
#define tiffredef_H

#define _TIFFDefaultStripSize           vspdft__TIFFDefaultStripSize
#define _TIFFDefaultTileSize            vspdft__TIFFDefaultTileSize
#define _TIFFFax3fillruns               vspdft__TIFFFax3fillruns
#define _TIFFFieldWithTag               vspdft__TIFFFieldWithTag
#define _TIFFFindFieldInfo              vspdft__TIFFFindFieldInfo
#define _TIFFfree                       vspdft__TIFFfree
#define _TIFFgetMode                    vspdft__TIFFgetMode
#define _TIFFmalloc                     vspdft__TIFFmalloc
#define _TIFFmemcmp                     vspdft__TIFFmemcmp
#define _TIFFmemcpy                     vspdft__TIFFmemcpy
#define _TIFFmemset                     vspdft__TIFFmemset
#define _TIFFMergeFieldInfo             vspdft__TIFFMergeFieldInfo
#define _TIFFNoPostDecode               vspdft__TIFFNoPostDecode
#define _TIFFNoPreCode                  vspdft__TIFFNoPreCode
#define _TIFFNoRowDecode                vspdft__TIFFNoRowDecode
#define _TIFFNoRowEncode                vspdft__TIFFNoRowEncode
#define _TIFFNoSeek                     vspdft__TIFFNoSeek
#define _TIFFNoStripDecode              vspdft__TIFFNoStripDecode
#define _TIFFNoStripEncode              vspdft__TIFFNoStripEncode
#define _TIFFNoTileDecode               vspdft__TIFFNoTileDecode
#define _TIFFNoTileEncode               vspdft__TIFFNoTileEncode
#define _TIFFprintAscii                 vspdft__TIFFprintAscii
#define _TIFFprintAsciiTag              vspdft__TIFFprintAsciiTag
#define _TIFFPrintFieldInfo             vspdft__TIFFPrintFieldInfo
#define _TIFFrealloc                    vspdft__TIFFrealloc
#define _TIFFSampleToTagType            vspdft__TIFFSampleToTagType
#define _TIFFsetByteArray               vspdft__TIFFsetByteArray
#define _TIFFSetDefaultCompressionState vspdft__TIFFSetDefCompState
#define _TIFFsetDoubleArray             vspdft__TIFFsetDoubleArray
#define _TIFFsetFloatArray              vspdft__TIFFsetFloatArray
#define _TIFFsetLongArray               vspdft__TIFFsetLongArray
#define _TIFFsetShortArray              vspdft__TIFFsetShortArray
#define _TIFFsetString                  vspdft__TIFFsetString
#define _TIFFSetupFieldInfo             vspdft__TIFFSetupFieldInfo
#define _TIFFSwab16BitData              vspdft__TIFFSwab16BitData
#define _TIFFSwab32BitData              vspdft__TIFFSwab32BitData
#define _TIFFSwab64BitData              vspdft__TIFFSwab64BitData
#define CheckDirCount                   vspdft_CheckDirCount
#define ChopUpSingleUncompressedStrip   vspdft_ChopUpSingleUncompStrip
#define cl_hash                         vspdft_cl_hash
#define EstimateStripByteCounts         vspdft_EstimateStripByteCounts
#define find0span                       vspdft_find0span
#define find1span                       vspdft_find1span
#define gtStripContig                   vspdft_gtStripContig
#define gtStripSeparate                 vspdft_gtStripSeparate
#define gtTileContig                    vspdft_gtTileContig
#define gtTileSeparate                  vspdft_gtTileSeparate
#define horAcc16                        vspdft_horAcc16
#define horAcc8                         vspdft_horAcc8
#define horDiff16                       vspdft_horDiff16
#define horDiff8                        vspdft_horDiff8
#define jpeg_reset_huff_decode          vspdft_jpeg_reset_huff_decode
#define JPEGDecode                      vspdft_JPEGDecode
#define JPEGDecodeRaw                   vspdft_JPEGDecodeRaw
#define JPEGEncode                      vspdft_JPEGEncode
#define JPEGEncodeRaw                   vspdft_JPEGEncodeRaw
#define LogL10fromY                     vspdft_LogL10fromY
#define LogL10toY                       vspdft_LogL10toY
#define LogL16fromY                     vspdft_LogL16fromY
#define LogL16toY                       vspdft_LogL16toY
#define LogLuv24fromXYZ                 vspdft_LogLuv24fromXYZ
#define LogLuv24toXYZ                   vspdft_LogLuv24toXYZ
#define LogLuv32fromXYZ                 vspdft_LogLuv32fromXYZ
#define LogLuv32toXYZ                   vspdft_LogLuv32toXYZ
#define LZWDecode                       vspdft_LZWDecode
#define LZWDecodeCompat                 vspdft_LZWDecodeCompat
#define MissingRequired                 vspdft_MissingRequired
#define NotConfigured                   vspdft_NotConfigured
#define pickTileContigCase              vspdft_pickTileContigCase
#define pickTileSeparateCase            vspdft_pickTileSeparateCase
#define PixarLogDecode                  vspdft_PixarLogDecode
#define PixarLogEncode                  vspdft_PixarLogEncode
#define PredictorDecodeRow              vspdft_PredictorDecodeRow
#define PredictorDecodeTile             vspdft_PredictorDecodeTile
#define PredictorEncodeRow              vspdft_PredictorEncodeRow
#define PredictorEncodeTile             vspdft_PredictorEncodeTile
#define swabHorAcc16                    vspdft_swabHorAcc16
#define TIFFAppendToStrip               vspdft_TIFFAppendToStrip
#define TIFFCheckRead                   vspdft_TIFFCheckRead
#define TIFFCheckTile                   vspdft_TIFFCheckTile
#define TIFFClientOpen                  vspdft_TIFFClientOpen
#define TIFFClose                       vspdft_TIFFClose
#define TIFFComputeStrip                vspdft_TIFFComputeStrip
#define TIFFComputeTile                 vspdft_TIFFComputeTile
#define TIFFCreateDirectory             vspdft_TIFFCreateDirectory
#define TIFFCurrentDirectory            vspdft_TIFFCurrentDirectory
#define TIFFCurrentDirOffset            vspdft_TIFFCurrentDirOffset
#define TIFFCurrentRow                  vspdft_TIFFCurrentRow
#define TIFFCurrentStrip                vspdft_TIFFCurrentStrip
#define TIFFCurrentTile                 vspdft_TIFFCurrentTile
#define TIFFDefaultDirectory            vspdft_TIFFDefaultDirectory
#define TIFFDefaultStripSize            vspdft_TIFFDefaultStripSize
#define TIFFDefaultTileSize             vspdft_TIFFDefaultTileSize
#define TIFFError                       vspdft_TIFFError
#define TIFFFdOpen                      vspdft_TIFFFdOpen
#define TIFFFetchAnyArray               vspdft_TIFFFetchAnyArray
#define TIFFFetchData                   vspdft_TIFFFetchData
#define TIFFFetchDoubleArray            vspdft_TIFFFetchDoubleArray
#define TIFFFetchExtraSamples           vspdft_TIFFFetchExtraSamples
#define TIFFFetchFloat                  vspdft_TIFFFetchFloat
#define TIFFFetchFloatArray             vspdft_TIFFFetchFloatArray
#define TIFFFetchNormalTag              vspdft_TIFFFetchNormalTag
#define TIFFFetchPerSampleAnys          vspdft_TIFFFetchPerSampleAnys
#define TIFFFetchPerSampleShorts        vspdft_TIFFFetchPerSamplShorts
#define TIFFFetchRational               vspdft_TIFFFetchRational
#define TIFFFetchRefBlackWhite          vspdft_TIFFFetchRefBlackWhite
#define TIFFFetchShortArray             vspdft_TIFFFetchShortArray
#define TIFFFetchShortPair              vspdft_TIFFFetchShortPair
#define TIFFFetchString                 vspdft_TIFFFetchString
#define TIFFFetchStripThing             vspdft_TIFFFetchStripThing
#define TIFFFileName                    vspdft_TIFFFileName
#define TIFFFileno                      vspdft_TIFFFileno
#define TIFFFillStrip                   vspdft_TIFFFillStrip
#define TIFFFillTile                    vspdft_TIFFFillTile
#define TIFFFindCODEC                   vspdft_TIFFFindCODEC
#define TIFFFlush                       vspdft_TIFFFlush
#define TIFFFlushData                   vspdft_TIFFFlushData
#define TIFFFlushData1                  vspdft_TIFFFlushData1
#define TIFFFreeDirectory               vspdft_TIFFFreeDirectory
#define TIFFGetBitRevTable              vspdft_TIFFGetBitRevTable
#define TIFFGetField                    vspdft_TIFFGetField
#define TIFFGetFieldDefaulted           vspdft_TIFFGetFieldDefaulted
#define TIFFGetMode                     vspdft_TIFFGetMode
#define TIFFGetVersion                  vspdft_TIFFGetVersion
#define TIFFGrowStrips                  vspdft_TIFFGrowStrips
#define TIFFInitDumpMode                vspdft_TIFFInitDumpMode
#define TIFFInitJPEG                    vspdft_TIFFInitJPEG
#define TIFFInitLZW                     vspdft_TIFFInitLZW
#define TIFFInitNeXT                    vspdft_TIFFInitNeXT
#define TIFFInitOJPEG                   vspdft_TIFFInitOJPEG
#define TIFFInitPackBits                vspdft_TIFFInitPackBits
#define TIFFInitSGILog                  vspdft_TIFFInitSGILog
#define TIFFInitThunderScan             vspdft_TIFFInitThunderScan
#define TIFFInitZIP                     vspdft_TIFFInitZIP
#define TIFFIsByteSwapped               vspdft_TIFFIsByteSwapped
#define TIFFIsMSB2LSB                   vspdft_TIFFIsMSB2LSB
#define TIFFIsTiled                     vspdft_TIFFIsTiled
#define TIFFIsUpSampled                 vspdft_TIFFIsUpSampled
#define TIFFLastDirectory               vspdft_TIFFLastDirectory
#define TIFFLinkDirectory               vspdft_TIFFLinkDirectory
#define TIFFNumberOfDirectories         vspdft_TIFFNumberOfDirectories
#define TIFFNumberOfStrips              vspdft_TIFFNumberOfStrips
#define TIFFNumberOfTiles               vspdft_TIFFNumberOfTiles
#define TIFFOpen                        vspdft_TIFFOpen
#define TIFFPredictorInit               vspdft_TIFFPredictorInit
#define TIFFPrintDirectory              vspdft_TIFFPrintDirectory
#define TIFFRasterScanlineSize          vspdft_TIFFRasterScanlineSize
#define TIFFReadBufferSetup             vspdft_TIFFReadBufferSetup
#define TIFFReadDirectory               vspdft_TIFFReadDirectory
#define TIFFReadEncodedStrip            vspdft_TIFFReadEncodedStrip
#define TIFFReadEncodedTile             vspdft_TIFFReadEncodedTile
#define TIFFReadRawStrip                vspdft_TIFFReadRawStrip
#define TIFFReadRawTile                 vspdft_TIFFReadRawTile
#define TIFFReadRGBAImage               vspdft_TIFFReadRGBAImage
#define TIFFReadRGBAStrip               vspdft_TIFFReadRGBAStrip
#define TIFFReadRGBATile                vspdft_TIFFReadRGBATile
#define TIFFReadScanline                vspdft_TIFFReadScanline
#define TIFFReadTile                    vspdft_TIFFReadTile
#define TIFFReassignTagToIgnore         vspdft_TIFFReassignTagToIgnore
#define TIFFRegisterCODEC               vspdft_TIFFRegisterCODEC
#define TIFFReverseBits                 vspdft_TIFFReverseBits
#define TIFFRewriteDirectory            vspdft_TIFFRewriteDirectory
#define TIFFRGBAImageBegin              vspdft_TIFFRGBAImageBegin
#define TIFFRGBAImageEnd                vspdft_TIFFRGBAImageEnd
#define TIFFRGBAImageGet                vspdft_TIFFRGBAImageGet
#define TIFFRGBAImageOK                 vspdft_TIFFRGBAImageOK
#define TIFFScanlineSize                vspdft_TIFFScanlineSize
#define TIFFSetCompressionScheme        vspdft_TIFFSetCompScheme
#define TIFFSetDefaultCompressionState  vspdft_TIFFSetDefaultCompState
#define TIFFSetDirectory                vspdft_TIFFSetDirectory
#define TIFFSetErrorHandler             vspdft_TIFFSetErrorHandler
#define TIFFSetField                    vspdft_TIFFSetField
#define TIFFSetSubDirectory             vspdft_TIFFSetSubDirectory
#define TIFFSetTagExtender              vspdft_TIFFSetTagExtender
#define TIFFSetupShortLong              vspdft_TIFFSetupShortLong
#define TIFFSetupShortPair              vspdft_TIFFSetupShortPair
#define TIFFSetupStrips                 vspdft_TIFFSetupStrips
#define TIFFSetWarningHandler           vspdft_TIFFSetWarningHandler
#define TIFFSetWriteOffset              vspdft_TIFFSetWriteOffset
#define TIFFStartStrip                  vspdft_TIFFStartStrip
#define TIFFStartTile                   vspdft_TIFFStartTile
#define TIFFStripSize                   vspdft_TIFFStripSize
#define TIFFSwabArrayOfDouble           vspdft_TIFFSwabArrayOfDouble
#define TIFFSwabArrayOfLong             vspdft_TIFFSwabArrayOfLong
#define TIFFSwabArrayOfShort            vspdft_TIFFSwabArrayOfShort
#define TIFFSwabDouble                  vspdft_TIFFSwabDouble
#define TIFFSwabLong                    vspdft_TIFFSwabLong
#define TIFFSwabShort                   vspdft_TIFFSwabShort
#define TIFFTileRowSize                 vspdft_TIFFTileRowSize
#define TIFFTileSize                    vspdft_TIFFTileSize
#define TIFFUnlinkDirectory             vspdft_TIFFUnlinkDirectory
#define TIFFUnRegisterCODEC             vspdft_TIFFUnRegisterCODEC
#define TIFFVGetField                   vspdft_TIFFVGetField
#define TIFFVGetFieldDefaulted          vspdft_TIFFVGetFieldDefaulted
#define TIFFVSetField                   vspdft_TIFFVSetField
#define TIFFVStripSize                  vspdft_TIFFVStripSize
#define TIFFVTileSize                   vspdft_TIFFVTileSize
#define TIFFWarning                     vspdft_TIFFWarning
#define TIFFWriteAnyArray               vspdft_TIFFWriteAnyArray
#define TIFFWriteBufferSetup            vspdft_TIFFWriteBufferSetup
#define TIFFWriteByteArray              vspdft_TIFFWriteByteArray
#define TIFFWriteCheck                  vspdft_TIFFWriteCheck
#define TIFFWriteData                   vspdft_TIFFWriteData
#define TIFFWriteDirectory              vspdft_TIFFWriteDirectory
#define TIFFWriteDoubleArray            vspdft_TIFFWriteDoubleArray
#define TIFFWriteEncodedStrip           vspdft_TIFFWriteEncodedStrip
#define TIFFWriteEncodedTile            vspdft_TIFFWriteEncodedTile
#define TIFFWriteFloatArray             vspdft_TIFFWriteFloatArray
#define TIFFWriteInkNames               vspdft_TIFFWriteInkNames
#define TIFFWriteLongArray              vspdft_TIFFWriteLongArray
#define TIFFWriteNormalTag              vspdft_TIFFWriteNormalTag
#define TIFFWritePerSampleAnys          vspdft_TIFFWritePerSampleAnys
#define TIFFWritePerSampleShorts        vspdft_TIFFWritePerSampShorts
#define TIFFWriteRationalArray          vspdft_TIFFWriteRationalArray
#define TIFFWriteRawStrip               vspdft_TIFFWriteRawStrip
#define TIFFWriteRawTile                vspdft_TIFFWriteRawTile
#define TIFFWriteScanline               vspdft_TIFFWriteScanline
#define TIFFWriteShortArray             vspdft_TIFFWriteShortArray
#define TIFFWriteShortTable             vspdft_TIFFWriteShortTable
#define TIFFWriteTile                   vspdft_TIFFWriteTile
#define TIFFWriteTransferFunction       vspdft_TIFFWriteTransferFunc
#define uv_decode                       vspdft_uv_decode
#define uv_encode                       vspdft_uv_encode
#define XYZtoRGB24                      vspdft_XYZtoRGB24
#define ZIPDecode                       vspdft_ZIPDecode
#define ZIPEncode                       vspdft_ZIPEn


#endif 
