#ifndef H_TIFFUNCRENAME
#define H_TIFFUNCRENAME

#define _TIFFDefaultStripSize           VersyPDF__TIFFDefaultStripSize
#define _TIFFDefaultTileSize            VersyPDF__TIFFDefaultTileSize
#define _TIFFFax3fillruns               VersyPDF__TIFFFax3fillruns
#define _TIFFFieldWithTag               VersyPDF__TIFFFieldWithTag
#define _TIFFFindFieldInfo              VersyPDF__TIFFFindFieldInfo
//#define _TIFFfree                       VersyPDF__TIFFfree
#define _TIFFgetMode                    VersyPDF__TIFFgetMode
//#define _TIFFmalloc                     VersyPDF__TIFFmalloc
#define _TIFFmemcmp                     VersyPDF__TIFFmemcmp
#define _TIFFmemcpy                     VersyPDF__TIFFmemcpy
#define _TIFFmemset                     VersyPDF__TIFFmemset
#define _TIFFMergeFieldInfo             VersyPDF__TIFFMergeFieldInfo
#define _TIFFNoPostDecode               VersyPDF__TIFFNoPostDecode
#define _TIFFNoPreCode                  VersyPDF__TIFFNoPreCode
#define _TIFFNoRowDecode                VersyPDF__TIFFNoRowDecode
#define _TIFFNoRowEncode                VersyPDF__TIFFNoRowEncode
#define _TIFFNoSeek                     VersyPDF__TIFFNoSeek
#define _TIFFNoStripDecode              VersyPDF__TIFFNoStripDecode
#define _TIFFNoStripEncode              VersyPDF__TIFFNoStripEncode
#define _TIFFNoTileDecode               VersyPDF__TIFFNoTileDecode
#define _TIFFNoTileEncode               VersyPDF__TIFFNoTileEncode
#define _TIFFprintAscii                 VersyPDF__TIFFprintAscii
#define _TIFFprintAsciiTag              VersyPDF__TIFFprintAsciiTag
#define _TIFFPrintFieldInfo             VersyPDF__TIFFPrintFieldInfo
//#define _TIFFrealloc                    VersyPDF__TIFFrealloc
#define _TIFFSampleToTagType            VersyPDF__TIFFSampleToTagType
#define _TIFFsetByteArray               VersyPDF__TIFFsetByteArray
#define _TIFFSetDefaultCompressionState VersyPDF__TIFFSetDefCompState
#define _TIFFsetDoubleArray             VersyPDF__TIFFsetDoubleArray
#define _TIFFsetFloatArray              VersyPDF__TIFFsetFloatArray
#define _TIFFsetLongArray               VersyPDF__TIFFsetLongArray
#define _TIFFsetShortArray              VersyPDF__TIFFsetShortArray
#define _TIFFsetString                  VersyPDF__TIFFsetString
#define _TIFFSetupFieldInfo             VersyPDF__TIFFSetupFieldInfo
#define _TIFFSwab16BitData              VersyPDF__TIFFSwab16BitData
#define _TIFFSwab32BitData              VersyPDF__TIFFSwab32BitData
#define _TIFFSwab64BitData              VersyPDF__TIFFSwab64BitData
#define CheckDirCount                   VersyPDF_CheckDirCount
#define ChopUpSingleUncompressedStrip   VersyPDF_ChopUpSingleUncompStrip
#define cl_hash                         VersyPDF_cl_hash
#define EstimateStripByteCounts         VersyPDF_EstimateStripByteCounts
#define find0span                       VersyPDF_find0span
#define find1span                       VersyPDF_find1span
#define gtStripContig                   VersyPDF_gtStripContig
#define gtStripSeparate                 VersyPDF_gtStripSeparate
#define gtTileContig                    VersyPDF_gtTileContig
#define gtTileSeparate                  VersyPDF_gtTileSeparate
#define horAcc16                        VersyPDF_horAcc16
#define horAcc8                         VersyPDF_horAcc8
#define horDiff16                       VersyPDF_horDiff16
#define horDiff8                        VersyPDF_horDiff8
#define JPEGDecode                      VersyPDF_JPEGDecode
#define JPEGDecodeRaw                   VersyPDF_JPEGDecodeRaw
#define JPEGEncode                      VersyPDF_JPEGEncode
#define JPEGEncodeRaw                   VersyPDF_JPEGEncodeRaw
#define LogL10fromY                     VersyPDF_LogL10fromY
#define LogL10toY                       VersyPDF_LogL10toY
#define LogL16fromY                     VersyPDF_LogL16fromY
#define LogL16toY                       VersyPDF_LogL16toY
#define LogLuv24fromXYZ                 VersyPDF_LogLuv24fromXYZ
#define LogLuv24toXYZ                   VersyPDF_LogLuv24toXYZ
#define LogLuv32fromXYZ                 VersyPDF_LogLuv32fromXYZ
#define LogLuv32toXYZ                   VersyPDF_LogLuv32toXYZ
#define LZWDecode                       VersyPDF_LZWDecode
#define LZWDecodeCompat                 VersyPDF_LZWDecodeCompat
#define MissingRequired                 VersyPDF_MissingRequired
#define NotConfigured                   VersyPDF_NotConfigured
#define pickTileContigCase              VersyPDF_pickTileContigCase
#define pickTileSeparateCase            VersyPDF_pickTileSeparateCase
#define PixarLogDecode                  VersyPDF_PixarLogDecode
#define PixarLogEncode                  VersyPDF_PixarLogEncode
#define PredictorDecodeRow              VersyPDF_PredictorDecodeRow
#define PredictorDecodeTile             VersyPDF_PredictorDecodeTile
#define PredictorEncodeRow              VersyPDF_PredictorEncodeRow
#define PredictorEncodeTile             VersyPDF_PredictorEncodeTile
#define swabHorAcc16                    VersyPDF_swabHorAcc16
#define TIFFAppendToStrip               VersyPDF_TIFFAppendToStrip
#define TIFFCheckRead                   VersyPDF_TIFFCheckRead
#define TIFFCheckTile                   VersyPDF_TIFFCheckTile
#define TIFFClientOpen                  VersyPDF_TIFFClientOpen
#define TIFFClose                       VersyPDF_TIFFClose
#define TIFFComputeStrip                VersyPDF_TIFFComputeStrip
#define TIFFComputeTile                 VersyPDF_TIFFComputeTile
#define TIFFCreateDirectory             VersyPDF_TIFFCreateDirectory
#define TIFFCurrentDirectory            VersyPDF_TIFFCurrentDirectory
#define TIFFCurrentDirOffset            VersyPDF_TIFFCurrentDirOffset
#define TIFFCurrentRow                  VersyPDF_TIFFCurrentRow
#define TIFFCurrentStrip                VersyPDF_TIFFCurrentStrip
#define TIFFCurrentTile                 VersyPDF_TIFFCurrentTile
#define TIFFDefaultDirectory            VersyPDF_TIFFDefaultDirectory
#define TIFFDefaultStripSize            VersyPDF_TIFFDefaultStripSize
#define TIFFDefaultTileSize             VersyPDF_TIFFDefaultTileSize
#define TIFFError                       VersyPDF_TIFFError
#define TIFFFdOpen                      VersyPDF_TIFFFdOpen
#define TIFFFetchAnyArray               VersyPDF_TIFFFetchAnyArray
#define TIFFFetchData                   VersyPDF_TIFFFetchData
#define TIFFFetchDoubleArray            VersyPDF_TIFFFetchDoubleArray
#define TIFFFetchExtraSamples           VersyPDF_TIFFFetchExtraSamples
#define TIFFFetchFloat                  VersyPDF_TIFFFetchFloat
#define TIFFFetchFloatArray             VersyPDF_TIFFFetchFloatArray
#define TIFFFetchNormalTag              VersyPDF_TIFFFetchNormalTag
#define TIFFFetchPerSampleAnys          VersyPDF_TIFFFetchPerSampleAnys
#define TIFFFetchPerSampleShorts        VersyPDF_TIFFFetchPerSamplShorts
#define TIFFFetchRational               VersyPDF_TIFFFetchRational
#define TIFFFetchRefBlackWhite          VersyPDF_TIFFFetchRefBlackWhite
#define TIFFFetchShortArray             VersyPDF_TIFFFetchShortArray
#define TIFFFetchShortPair              VersyPDF_TIFFFetchShortPair
#define TIFFFetchString                 VersyPDF_TIFFFetchString
#define TIFFFetchStripThing             VersyPDF_TIFFFetchStripThing
#define TIFFFileName                    VersyPDF_TIFFFileName
#define TIFFFileno                      VersyPDF_TIFFFileno
#define TIFFFillStrip                   VersyPDF_TIFFFillStrip
#define TIFFFillTile                    VersyPDF_TIFFFillTile
#define TIFFFindCODEC                   VersyPDF_TIFFFindCODEC
#define TIFFFlush                       VersyPDF_TIFFFlush
#define TIFFFlushData                   VersyPDF_TIFFFlushData
#define TIFFFlushData1                  VersyPDF_TIFFFlushData1
#define TIFFFreeDirectory               VersyPDF_TIFFFreeDirectory
#define TIFFGetBitRevTable              VersyPDF_TIFFGetBitRevTable
#define TIFFGetField                    VersyPDF_TIFFGetField
#define TIFFGetFieldDefaulted           VersyPDF_TIFFGetFieldDefaulted
#define TIFFGetMode                     VersyPDF_TIFFGetMode
#define TIFFGetVersion                  VersyPDF_TIFFGetVersion
#define TIFFGrowStrips                  VersyPDF_TIFFGrowStrips
#define TIFFInitDumpMode                VersyPDF_TIFFInitDumpMode

#ifdef JPEG_SUPPORT
#define TIFFInitJPEG                    VersyPDF_TIFFInitJPEG
#endif

#define TIFFInitLZW                     VersyPDF_TIFFInitLZW
#define TIFFInitNeXT                    VersyPDF_TIFFInitNeXT

#ifdef OJPEG_SUPPORT
#define TIFFInitOJPEG                   VersyPDF_TIFFInitOJPEG
#endif

#define TIFFInitPackBits                VersyPDF_TIFFInitPackBits
#define TIFFInitSGILog                  VersyPDF_TIFFInitSGILog
#define TIFFInitThunderScan             VersyPDF_TIFFInitThunderScan

#ifdef ZIP_SUPPORT
#define TIFFInitZIP                     VersyPDF_TIFFInitZIP
#endif

#define TIFFIsByteSwapped               VersyPDF_TIFFIsByteSwapped
#define TIFFIsMSB2LSB                   VersyPDF_TIFFIsMSB2LSB
#define TIFFIsTiled                     VersyPDF_TIFFIsTiled
#define TIFFIsUpSampled                 VersyPDF_TIFFIsUpSampled
#define TIFFLastDirectory               VersyPDF_TIFFLastDirectory
#define TIFFLinkDirectory               VersyPDF_TIFFLinkDirectory
#define TIFFNumberOfDirectories         VersyPDF_TIFFNumberOfDirectories
#define TIFFNumberOfStrips              VersyPDF_TIFFNumberOfStrips
#define TIFFNumberOfTiles               VersyPDF_TIFFNumberOfTiles
#define TIFFOpen                        VersyPDF_TIFFOpen
#define TIFFPredictorInit               VersyPDF_TIFFPredictorInit
#define TIFFPrintDirectory              VersyPDF_TIFFPrintDirectory
#define TIFFRasterScanlineSize          VersyPDF_TIFFRasterScanlineSize
#define TIFFReadBufferSetup             VersyPDF_TIFFReadBufferSetup
#define TIFFReadDirectory               VersyPDF_TIFFReadDirectory
#define TIFFReadEncodedStrip            VersyPDF_TIFFReadEncodedStrip
#define TIFFReadEncodedTile             VersyPDF_TIFFReadEncodedTile
#define TIFFReadRawStrip                VersyPDF_TIFFReadRawStrip
#define TIFFReadRawTile                 VersyPDF_TIFFReadRawTile
#define TIFFReadRGBAImage               VersyPDF_TIFFReadRGBAImage
#define TIFFReadRGBAStrip               VersyPDF_TIFFReadRGBAStrip
#define TIFFReadRGBATile                VersyPDF_TIFFReadRGBATile
#define TIFFReadScanline                VersyPDF_TIFFReadScanline
#define TIFFReadTile                    VersyPDF_TIFFReadTile
#define TIFFReassignTagToIgnore         VersyPDF_TIFFReassignTagToIgnore
#define TIFFRegisterCODEC               VersyPDF_TIFFRegisterCODEC
#define TIFFReverseBits                 VersyPDF_TIFFReverseBits
#define TIFFRewriteDirectory            VersyPDF_TIFFRewriteDirectory
#define TIFFRGBAImageBegin              VersyPDF_TIFFRGBAImageBegin
#define TIFFRGBAImageEnd                VersyPDF_TIFFRGBAImageEnd
#define TIFFRGBAImageGet                VersyPDF_TIFFRGBAImageGet
#define TIFFRGBAImageOK                 VersyPDF_TIFFRGBAImageOK
#define TIFFScanlineSize                VersyPDF_TIFFScanlineSize
#define TIFFSetCompressionScheme        VersyPDF_TIFFSetCompScheme
#define TIFFSetDefaultCompressionState  VersyPDF_TIFFSetDefaultCompState
#define TIFFSetDirectory                VersyPDF_TIFFSetDirectory
#define TIFFSetErrorHandler             VersyPDF_TIFFSetErrorHandler
#define TIFFSetField                    VersyPDF_TIFFSetField
#define TIFFSetSubDirectory             VersyPDF_TIFFSetSubDirectory
#define TIFFSetTagExtender              VersyPDF_TIFFSetTagExtender
#define TIFFSetupShortLong              VersyPDF_TIFFSetupShortLong
#define TIFFSetupShortPair              VersyPDF_TIFFSetupShortPair
#define TIFFSetupStrips                 VersyPDF_TIFFSetupStrips
#define TIFFSetWarningHandler           VersyPDF_TIFFSetWarningHandler
#define TIFFSetWriteOffset              VersyPDF_TIFFSetWriteOffset
#define TIFFStartStrip                  VersyPDF_TIFFStartStrip
#define TIFFStartTile                   VersyPDF_TIFFStartTile
#define TIFFStripSize                   VersyPDF_TIFFStripSize
#define TIFFSwabArrayOfLong             VersyPDF_TIFFSwabArrayOfLong           
#define TIFFSwabArrayOfShort            VersyPDF_TIFFSwabArrayOfShort
#define TIFFSwabDouble                  VersyPDF_TIFFSwabDouble
#define TIFFSwabLong                    VersyPDF_TIFFSwabLong
#define TIFFSwabShort                   VersyPDF_TIFFSwabShort
#define TIFFTileRowSize                 VersyPDF_TIFFTileRowSize
#define TIFFTileSize                    VersyPDF_TIFFTileSize
#define TIFFUnlinkDirectory             VersyPDF_TIFFUnlinkDirectory
#define TIFFUnRegisterCODEC             VersyPDF_TIFFUnRegisterCODEC
#define TIFFVGetField                   VersyPDF_TIFFVGetField
#define TIFFVGetFieldDefaulted          VersyPDF_TIFFVGetFieldDefaulted
#define TIFFVSetField                   VersyPDF_TIFFVSetField
#define TIFFVStripSize                  VersyPDF_TIFFVStripSize
#define TIFFVTileSize                   VersyPDF_TIFFVTileSize
#define TIFFWarning                     VersyPDF_TIFFWarning
#define TIFFWriteAnyArray               VersyPDF_TIFFWriteAnyArray
#define TIFFWriteBufferSetup            VersyPDF_TIFFWriteBufferSetup
#define TIFFWriteByteArray              VersyPDF_TIFFWriteByteArray
#define TIFFWriteCheck                  VersyPDF_TIFFWriteCheck
#define TIFFWriteData                   VersyPDF_TIFFWriteData
#define TIFFWriteDirectory              VersyPDF_TIFFWriteDirectory
#define TIFFWriteDoubleArray            VersyPDF_TIFFWriteDoubleArray
#define TIFFWriteEncodedStrip           VersyPDF_TIFFWriteEncodedStrip
#define TIFFWriteEncodedTile            VersyPDF_TIFFWriteEncodedTile
#define TIFFWriteFloatArray             VersyPDF_TIFFWriteFloatArray
#define TIFFWriteInkNames               VersyPDF_TIFFWriteInkNames
#define TIFFWriteLongArray              VersyPDF_TIFFWriteLongArray
#define TIFFWriteNormalTag              VersyPDF_TIFFWriteNormalTag
#define TIFFWritePerSampleAnys          VersyPDF_TIFFWritePerSampleAnys
#define TIFFWritePerSampleShorts        VersyPDF_TIFFWritePerSampShorts
#define TIFFWriteRationalArray          VersyPDF_TIFFWriteRationalArray
#define TIFFWriteRawStrip               VersyPDF_TIFFWriteRawStrip
#define TIFFWriteRawTile                VersyPDF_TIFFWriteRawTile
#define TIFFWriteScanline               VersyPDF_TIFFWriteScanline
#define TIFFWriteShortArray             VersyPDF_TIFFWriteShortArray
#define TIFFWriteShortTable             VersyPDF_TIFFWriteShortTable
#define TIFFWriteTile                   VersyPDF_TIFFWriteTile
#define TIFFWriteTransferFunction       VersyPDF_TIFFWriteTransferFunc
#define uv_decode                       VersyPDF_uv_decode
#define uv_encode                       VersyPDF_uv_encode
#define XYZtoRGB24                      VersyPDF_XYZtoRGB24
#define ZIPDecode                       VersyPDF_ZIPDecode
#define ZIPEncode                       VersyPDF_ZIPEn
#define TIFFFaxMainTable                VersyPDF_TIFFFaxMainTable
#define TIFFFaxWhiteTable               VersyPDF_TIFFFaxWhiteTable
#define TIFFFaxBlackTable               VersyPDF_TIFFFaxBlackTable
#define tiffDataWidth			VersyPDF_tiffDataWidth
#define _TIFFBuiltinCODECS		VersyPDF__TIFFBuiltinCODECS
#define  _TIFFMultiply32   		VersyPDF__TIFFMultiply32
#define  _TIFFMultiply64   		VersyPDF__TIFFMultiply64
#define  _TIFFCheckRealloc   		VersyPDF__TIFFCheckRealloc
#define  _TIFFCheckMalloc   		VersyPDF__TIFFCheckMalloc
#define  _TIFFUInt64ToFloat   		VersyPDF__TIFFUInt64ToFloat
#define  _TIFFUInt64ToDouble   		VersyPDF__TIFFUInt64ToDouble
#define  TIFFCleanup   			VersyPDF_TIFFCleanup
#define  TIFFIsCODECConfigured   	VersyPDF_TIFFIsCODECConfigured
#define  TIFFCIELabToXYZ   		VersyPDF_TIFFCIELabToXYZ
#define  TIFFXYZToRGB   		VersyPDF_TIFFXYZToRGB
#define  TIFFCIELabToRGBInit   		VersyPDF_TIFFCIELabToRGBInit
#define  TIFFYCbCrtoRGB   		VersyPDF_TIFFYCbCrtoRGB
#define  TIFFYCbCrToRGBInit   		VersyPDF_TIFFYCbCrToRGBInit
#define  _TIFFNoFixupTags   		VersyPDF__TIFFNoFixupTags
#define  TIFFGetConfiguredCODECs   	VersyPDF_TIFFGetConfiguredCODECs
#define  _TIFFsetNString   		VersyPDF__TIFFsetNString
#define  _TIFFsetLong8Array   		VersyPDF__TIFFsetLong8Array
#define  TIFFUnsetField   		VersyPDF_TIFFUnsetField
#define  TIFFCreateCustomDirectory   	VersyPDF_TIFFCreateCustomDirectory
#define  TIFFCreateEXIFDirectory   	VersyPDF_TIFFCreateEXIFDirectory
#define  _TIFFGetFields   VersyPDF__TIFFGetFields
#define  _TIFFGetExifFields   VersyPDF__TIFFGetExifFields
#define  _TIFFSetupFields   VersyPDF__TIFFSetupFields
#define  _TIFFMergeFields   VersyPDF__TIFFMergeFields
#define  TIFFDataWidth   VersyPDF_TIFFDataWidth
#define  _TIFFDataSize   VersyPDF__TIFFDataSize
#define  TIFFFindField   VersyPDF_TIFFFindField
#define  _TIFFFindFieldByName   VersyPDF__TIFFFindFieldByName
#define  TIFFFieldWithTag   VersyPDF_TIFFFieldWithTag
#define  TIFFFieldWithName   VersyPDF_TIFFFieldWithName
#define  TIFFFieldTag   VersyPDF_TIFFFieldTag
#define  TIFFFieldName   VersyPDF_TIFFFieldName
#define  TIFFFieldDataType   VersyPDF_TIFFFieldDataType
#define  TIFFFieldPassCount   VersyPDF_TIFFFieldPassCount
#define  TIFFFieldReadCount   VersyPDF_TIFFFieldReadCount
#define  TIFFFieldWriteCount   VersyPDF_TIFFFieldWriteCount
#define  _TIFFFindOrRegisterField   VersyPDF__TIFFFindOrRegisterField
#define  _TIFFCreateAnonField   VersyPDF__TIFFCreateAnonField
#define  TIFFMergeFieldInfo   VersyPDF_TIFFMergeFieldInfo
#define  TIFFReadCustomDirectory   VersyPDF_TIFFReadCustomDirectory
#define  TIFFReadEXIFDirectory   VersyPDF_TIFFReadEXIFDirectory
#define  _TIFFFillStriles   VersyPDF__TIFFFillStriles
#define  TIFFCheckpointDirectory   VersyPDF_TIFFCheckpointDirectory
#define  TIFFWriteCustomDirectory   VersyPDF_TIFFWriteCustomDirectory
#define  _TIFFRewriteField   VersyPDF__TIFFRewriteField
#define  TIFFSetErrorHandlerExt   VersyPDF_TIFFSetErrorHandlerExt
#define  TIFFErrorExt   VersyPDF_TIFFErrorExt
#define  _TIFFerrorHandlerExt   VersyPDF__TIFFerrorHandlerExt
#define  TIFFGetTagListCount   VersyPDF_TIFFGetTagListCount
#define  TIFFGetTagListEntry   VersyPDF_TIFFGetTagListEntry
#define  TIFFAccessTagMethods   VersyPDF_TIFFAccessTagMethods
#define  TIFFGetClientInfo   VersyPDF_TIFFGetClientInfo
#define  TIFFSetClientInfo   VersyPDF_TIFFSetClientInfo
#define  TIFFInitCCITTFax3   VersyPDF_TIFFInitCCITTFax3
#define  TIFFInitCCITTFax4   VersyPDF_TIFFInitCCITTFax4
#define  TIFFInitCCITTRLE   VersyPDF_TIFFInitCCITTRLE
#define  TIFFInitCCITTRLEW   VersyPDF_TIFFInitCCITTRLEW
#define  TIFFFaxWhiteCodes   VersyPDF_TIFFFaxWhiteCodes
#define  TIFFFaxBlackCodes   VersyPDF_TIFFFaxBlackCodes
#define  TIFFReadRGBAImageOriented   VersyPDF_TIFFReadRGBAImageOriented
#define  TIFFSetFileName   VersyPDF_TIFFSetFileName
#define  TIFFSetFileno   VersyPDF_TIFFSetFileno
#define  TIFFClientdata   VersyPDF_TIFFClientdata
#define  TIFFSetClientdata   VersyPDF_TIFFSetClientdata
#define  TIFFSetMode   VersyPDF_TIFFSetMode
#define  TIFFIsBigEndian   VersyPDF_TIFFIsBigEndian
#define  TIFFGetReadProc   VersyPDF_TIFFGetReadProc
#define  TIFFGetWriteProc   VersyPDF_TIFFGetWriteProc
#define  TIFFGetSeekProc   VersyPDF_TIFFGetSeekProc
#define  TIFFGetCloseProc   VersyPDF_TIFFGetCloseProc
#define  TIFFGetSizeProc   VersyPDF_TIFFGetSizeProc
#define  TIFFGetMapFileProc   VersyPDF_TIFFGetMapFileProc
#define  TIFFGetUnmapFileProc   VersyPDF_TIFFGetUnmapFileProc
#define  TIFFPredictorCleanup   VersyPDF_TIFFPredictorCleanup
#define  _TIFFSwab24BitData   VersyPDF__TIFFSwab24BitData
#define  TIFFVStripSize64   VersyPDF_TIFFVStripSize64
#define  TIFFRawStripSize64   VersyPDF_TIFFRawStripSize64
#define  TIFFRawStripSize   VersyPDF_TIFFRawStripSize
#define  TIFFStripSize64   VersyPDF_TIFFStripSize64
#define  TIFFScanlineSize64   VersyPDF_TIFFScanlineSize64
#define  TIFFRasterScanlineSize64   VersyPDF_TIFFRasterScanlineSize64
#define  TIFFSwabLong8   VersyPDF_TIFFSwabLong8
#define  TIFFSwabArrayOfTriples   VersyPDF_TIFFSwabArrayOfTriples
#define  TIFFSwabArrayOfLong8   VersyPDF_TIFFSwabArrayOfLong8
#define  TIFFSwabFloat   VersyPDF_TIFFSwabFloat
#define  TIFFSwabArrayOfFloat   VersyPDF_TIFFSwabArrayOfFloat
#define  TIFFSwabArrayOfDouble   VersyPDF_TIFFSwabArrayOfDouble
#define  TIFFTileRowSize64   VersyPDF_TIFFTileRowSize64
#define  TIFFVTileSize64   VersyPDF_TIFFVTileSize64
#define  TIFFTileSize64   VersyPDF_TIFFTileSize64
#define  TIFFSetWarningHandlerExt   VersyPDF_TIFFSetWarningHandlerExt
#define  TIFFWarningExt   VersyPDF_TIFFWarningExt
#define  _TIFFwarningHandlerExt   VersyPDF__TIFFwarningHandlerExt
#define  TIFFOpenW   VersyPDF_TIFFOpenW
#define  _TIFFmalloc   VersyPDF__TIFFmalloc
#define  _TIFFfree   VersyPDF__TIFFfree
#define  _TIFFrealloc   VersyPDF__TIFFrealloc
#define  _TIFFwarningHandler   VersyPDF__TIFFwarningHandler
#define  _TIFFerrorHandler   VersyPDF__TIFFerrorHandler


#endif
