/*********************************************************************

This file is part of the VersyPDF project.
Copyright (C) 2005 - 2016 Sybrex Systems Ltd. All rights reserved.
Authors: Vadzim Shakun , et al.

VersyPDF is free software: you can redistribute it and/or modify it 
under the terms of the GNU Affero General Public License as published 
by the Free Software Foundation, either version 3 of the License, or 
(at your option) any later version, with the addition of the following 
permission added to Section 15 as permitted in Section 7(a):
FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY 
SYBREX SYSTEMS. SYBREX SYSTEMS DISCLAIMS THE WARRANTY OF NON 
INFRINGEMENT OF THIRD PARTY RIGHTS.
                    
VersyPDF is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU Affero General Public License for more details.
                                                                   
In accordance with Section 7(b) of the GNU Affero General Public License, 
a covered work must retain the producer line in every PDF that is created 
or manipulated using VersyPDF.

You can be released from the requirements of the license by purchasing 
a commercial license. Buying such a license is mandatory as soon as you 
develop commercial activities involving VersyPDF without disclosing 
the source code of your own applications, offering paid services to customers 
as an ASP, serving PDFs on the fly in a commerce web application, 
or shipping VersyPDF with a closed source product.

For more information, please contact Sybrex Systems at http://www.sybrex.com

----------------------------------------------------------------------
VSStdFont.h
*********************************************************************/

#ifndef VSStdFont_H
#define VSStdFont_H
#ifndef __GNUC__ /* suppress gcc warning */
#pragma once
#endif /* __GNUC__ */

#include "../VSTypes.h"

#ifdef __cplusplus
extern "C"{
#endif
#define PDFChar_NULL 0
#define PDFChar_A 1
#define PDFChar_AE 2
#define PDFChar_Aacute 3
#define PDFChar_Acircumflex 4
#define PDFChar_Adieresis 5
#define PDFChar_Agrave 6
#define PDFChar_Aring 7
#define PDFChar_Atilde 8
#define PDFChar_B 9
#define PDFChar_C 10
#define PDFChar_Ccedilla 11
#define PDFChar_D 12
#define PDFChar_E 13
#define PDFChar_Eacute 14
#define PDFChar_Ecircumflex 15
#define PDFChar_Edieresis 16
#define PDFChar_Egrave 17
#define PDFChar_Eth 18
#define PDFChar_Euro 19
#define PDFChar_F 20
#define PDFChar_G 21
#define PDFChar_H 22
#define PDFChar_I 23
#define PDFChar_Iacute 24
#define PDFChar_Icircumflex 25
#define PDFChar_Idieresis 26
#define PDFChar_Igrave 27
#define PDFChar_J 28
#define PDFChar_K 29
#define PDFChar_L 30
#define PDFChar_Lslash 31
#define PDFChar_M 32
#define PDFChar_N 33
#define PDFChar_Ntilde 34
#define PDFChar_O 35
#define PDFChar_OE 36
#define PDFChar_Oacute 37
#define PDFChar_Ocircumflex 38
#define PDFChar_Odieresis 39
#define PDFChar_Ograve 40
#define PDFChar_Oslash 41
#define PDFChar_Otilde 42
#define PDFChar_P 43
#define PDFChar_Q 44
#define PDFChar_R 45
#define PDFChar_S 46
#define PDFChar_Scaron 47
#define PDFChar_T 48
#define PDFChar_Thorn 49
#define PDFChar_U 50
#define PDFChar_Uacute 51
#define PDFChar_Ucircumflex 52
#define PDFChar_Udieresis 53
#define PDFChar_Ugrave 54
#define PDFChar_V 55
#define PDFChar_W 56
#define PDFChar_X 57
#define PDFChar_Y 58
#define PDFChar_Yacute 59
#define PDFChar_Ydieresis 60
#define PDFChar_Z 61
#define PDFChar_Zcaron 62
#define PDFChar_a 63
#define PDFChar_aacute 64
#define PDFChar_acircumflex 65
#define PDFChar_acute 66
#define PDFChar_adieresis 67
#define PDFChar_ae 68
#define PDFChar_agrave 69
#define PDFChar_ampersand 70
#define PDFChar_aring 71
#define PDFChar_asciicircum 72
#define PDFChar_asciitilde 73
#define PDFChar_asterisk 74
#define PDFChar_at 75
#define PDFChar_atilde 76
#define PDFChar_b 77
#define PDFChar_backslash 78
#define PDFChar_bar 79
#define PDFChar_braceleft 80
#define PDFChar_braceright 81
#define PDFChar_bracketleft 82
#define PDFChar_bracketright 83
#define PDFChar_breve 84
#define PDFChar_brokenbar 85
#define PDFChar_bullet 86
#define PDFChar_c 87
#define PDFChar_caron 88
#define PDFChar_ccedilla 89
#define PDFChar_cedilla 90
#define PDFChar_cent 91
#define PDFChar_circumflex 92
#define PDFChar_colon 93
#define PDFChar_comma 94
#define PDFChar_copyright 95
#define PDFChar_currency 96
#define PDFChar_d 97
#define PDFChar_dagger 98
#define PDFChar_daggerdbl 99
#define PDFChar_degree 100
#define PDFChar_dieresis 101
#define PDFChar_divide 102
#define PDFChar_dollar 103
#define PDFChar_dotaccent 104
#define PDFChar_dotlessi 105
#define PDFChar_e 106
#define PDFChar_eacute 107
#define PDFChar_ecircumflex 108
#define PDFChar_edieresis 109
#define PDFChar_egrave 110
#define PDFChar_eight 111
#define PDFChar_ellipsis 112
#define PDFChar_emdash 113
#define PDFChar_endash 114
#define PDFChar_equal 115
#define PDFChar_eth 116
#define PDFChar_exclam 117
#define PDFChar_exclamdown 118
#define PDFChar_f 119
#define PDFChar_fi 120
#define PDFChar_five 121
#define PDFChar_fl 122
#define PDFChar_florin 123
#define PDFChar_four 124
#define PDFChar_fraction 125
#define PDFChar_g 126
#define PDFChar_germandbls 127
#define PDFChar_grave 128
#define PDFChar_greater 129
#define PDFChar_guillemotleft 130
#define PDFChar_guillemotright 131
#define PDFChar_guilsinglleft 132
#define PDFChar_guilsinglright 133
#define PDFChar_h 134
#define PDFChar_hungarumlaut 135
#define PDFChar_hyphen 136
#define PDFChar_i 137
#define PDFChar_iacute 138
#define PDFChar_icircumflex 139
#define PDFChar_idieresis 140
#define PDFChar_igrave 141
#define PDFChar_j 142
#define PDFChar_k 143
#define PDFChar_l 144
#define PDFChar_less 145
#define PDFChar_logicalnot 146
#define PDFChar_lslash 147
#define PDFChar_m 148
#define PDFChar_macron 149
#define PDFChar_minus 150
#define PDFChar_mu 151
#define PDFChar_multiply 152
#define PDFChar_n 153
#define PDFChar_nine 154
#define PDFChar_ntilde 155
#define PDFChar_numbersign 156
#define PDFChar_o 157
#define PDFChar_oacute 158
#define PDFChar_ocircumflex 159
#define PDFChar_odieresis 160
#define PDFChar_oe 161
#define PDFChar_ogonek 162
#define PDFChar_ograve 163
#define PDFChar_one 164
#define PDFChar_onehalf 165
#define PDFChar_onequarter 166
#define PDFChar_onesuperior 167
#define PDFChar_ordfeminine 168
#define PDFChar_ordmasculine 169
#define PDFChar_oslash 170
#define PDFChar_otilde 171
#define PDFChar_p 172
#define PDFChar_paragraph 173
#define PDFChar_parenleft 174
#define PDFChar_parenright 175
#define PDFChar_percent 176
#define PDFChar_period 177
#define PDFChar_periodcentered 178
#define PDFChar_perthousand 179
#define PDFChar_plus 180
#define PDFChar_plusminus 181
#define PDFChar_q 182
#define PDFChar_question 183
#define PDFChar_questiondown 184
#define PDFChar_quotedbl 185
#define PDFChar_quotedblbase 186
#define PDFChar_quotedblleft 187
#define PDFChar_quotedblright 188
#define PDFChar_quoteleft 189
#define PDFChar_quoteright 190
#define PDFChar_quotesinglbase 191
#define PDFChar_quotesingle 192
#define PDFChar_r 193
#define PDFChar_registered 194
#define PDFChar_ring 195
#define PDFChar_s 196
#define PDFChar_scaron 197
#define PDFChar_section 198
#define PDFChar_semicolon 199
#define PDFChar_seven 200
#define PDFChar_six 201
#define PDFChar_slash 202
#define PDFChar_space 203
#define PDFChar_sterling 204
#define PDFChar_t 205
#define PDFChar_thorn 206
#define PDFChar_three 207
#define PDFChar_threequarters 208
#define PDFChar_threesuperior 209
#define PDFChar_tilde 210
#define PDFChar_trademark 211
#define PDFChar_two 212
#define PDFChar_twosuperior 213
#define PDFChar_u 214
#define PDFChar_uacute 215
#define PDFChar_ucircumflex 216
#define PDFChar_udieresis 217
#define PDFChar_ugrave 218
#define PDFChar_underscore 219
#define PDFChar_v 220
#define PDFChar_w 221
#define PDFChar_x 222
#define PDFChar_y 223
#define PDFChar_yacute 224
#define PDFChar_ydieresis 225
#define PDFChar_yen 226
#define PDFChar_z 227
#define PDFChar_zcaron 228
#define PDFChar_zero 229

#define PDFSymbolChar_NULL 0
#define PDFSymbolChar_Alpha 1
#define PDFSymbolChar_Beta 2
#define PDFSymbolChar_Chi 3
#define PDFSymbolChar_Delta 4
#define PDFSymbolChar_Epsilon 5
#define PDFSymbolChar_Eta 6
#define PDFSymbolChar_Euro 7
#define PDFSymbolChar_Gamma 8
#define PDFSymbolChar_Ifraktur 9
#define PDFSymbolChar_Iota 10
#define PDFSymbolChar_Kappa 11
#define PDFSymbolChar_Lambda 12
#define PDFSymbolChar_Mu 13
#define PDFSymbolChar_Nu 14
#define PDFSymbolChar_Omega 15
#define PDFSymbolChar_Omicron 16
#define PDFSymbolChar_Phi 17
#define PDFSymbolChar_Pi 18
#define PDFSymbolChar_Psi 19
#define PDFSymbolChar_Rfraktur 20
#define PDFSymbolChar_Rho 21
#define PDFSymbolChar_Sigma 22
#define PDFSymbolChar_Tau 23
#define PDFSymbolChar_Theta 24
#define PDFSymbolChar_Upsilon 25
#define PDFSymbolChar_Upsilon1 26
#define PDFSymbolChar_Xi 27
#define PDFSymbolChar_Zeta 28
#define PDFSymbolChar_aleph 29
#define PDFSymbolChar_alpha 30
#define PDFSymbolChar_ampersand 31
#define PDFSymbolChar_angle 32
#define PDFSymbolChar_angleleft 33
#define PDFSymbolChar_angleright 34
#define PDFSymbolChar_approxequal 35
#define PDFSymbolChar_arrowboth 36
#define PDFSymbolChar_arrowdblboth 37
#define PDFSymbolChar_arrowdbldown 38
#define PDFSymbolChar_arrowdblleft 39
#define PDFSymbolChar_arrowdblright 40
#define PDFSymbolChar_arrowdblup 41
#define PDFSymbolChar_arrowdown 42
#define PDFSymbolChar_arrowhorizex 43
#define PDFSymbolChar_arrowleft 44
#define PDFSymbolChar_arrowright 45
#define PDFSymbolChar_arrowup 46
#define PDFSymbolChar_arrowvertex 47
#define PDFSymbolChar_asteriskmath 48
#define PDFSymbolChar_bar 49
#define PDFSymbolChar_beta 50
#define PDFSymbolChar_braceleft 51
#define PDFSymbolChar_braceright 52
#define PDFSymbolChar_bracelefttp 53
#define PDFSymbolChar_braceleftmid 54
#define PDFSymbolChar_braceleftbt 55
#define PDFSymbolChar_bracerighttp 56
#define PDFSymbolChar_bracerightmid 57
#define PDFSymbolChar_bracerightbt 58
#define PDFSymbolChar_braceex 59
#define PDFSymbolChar_bracketleft 60
#define PDFSymbolChar_bracketright 61
#define PDFSymbolChar_bracketlefttp 62
#define PDFSymbolChar_bracketleftex 63
#define PDFSymbolChar_bracketleftbt 64
#define PDFSymbolChar_bracketrighttp 65
#define PDFSymbolChar_bracketrightex 66
#define PDFSymbolChar_bracketrightbt 67
#define PDFSymbolChar_bullet 68
#define PDFSymbolChar_carriagereturn 69
#define PDFSymbolChar_chi 70
#define PDFSymbolChar_circlemultiply 71
#define PDFSymbolChar_circleplus 72
#define PDFSymbolChar_club 73
#define PDFSymbolChar_colon 74
#define PDFSymbolChar_comma 75
#define PDFSymbolChar_congruent 76
#define PDFSymbolChar_copyrightsans 77
#define PDFSymbolChar_copyrightserif 78
#define PDFSymbolChar_degree 79
#define PDFSymbolChar_delta 80
#define PDFSymbolChar_diamond 81
#define PDFSymbolChar_divide 82
#define PDFSymbolChar_dotmath 83
#define PDFSymbolChar_eight 84
#define PDFSymbolChar_element 85
#define PDFSymbolChar_ellipsis 86
#define PDFSymbolChar_emptyset 87
#define PDFSymbolChar_epsilon 88
#define PDFSymbolChar_equal 89
#define PDFSymbolChar_equivalence 90
#define PDFSymbolChar_eta 91
#define PDFSymbolChar_exclam 92
#define PDFSymbolChar_existential 93
#define PDFSymbolChar_five 94
#define PDFSymbolChar_florin 95
#define PDFSymbolChar_four 96
#define PDFSymbolChar_fraction 97
#define PDFSymbolChar_gamma 98
#define PDFSymbolChar_gradient 99
#define PDFSymbolChar_greater 100
#define PDFSymbolChar_greaterequal 101
#define PDFSymbolChar_heart 102
#define PDFSymbolChar_infinity 103
#define PDFSymbolChar_integral 104
#define PDFSymbolChar_integraltp 105
#define PDFSymbolChar_integralex 106
#define PDFSymbolChar_integralbt 107
#define PDFSymbolChar_intersection 108
#define PDFSymbolChar_iota 109
#define PDFSymbolChar_kappa 110
#define PDFSymbolChar_lambda 111
#define PDFSymbolChar_less 112
#define PDFSymbolChar_lessequal 113
#define PDFSymbolChar_logicaland 114
#define PDFSymbolChar_logicalnot 115
#define PDFSymbolChar_logicalor 116
#define PDFSymbolChar_lozenge 117
#define PDFSymbolChar_minus 118
#define PDFSymbolChar_minute 119
#define PDFSymbolChar_mu 120
#define PDFSymbolChar_multiply 121
#define PDFSymbolChar_nine 122
#define PDFSymbolChar_notelement 123
#define PDFSymbolChar_notequal 124
#define PDFSymbolChar_notsubset 125
#define PDFSymbolChar_nu 126
#define PDFSymbolChar_numbersign 127
#define PDFSymbolChar_omega 128
#define PDFSymbolChar_omega1 129
#define PDFSymbolChar_omicron 130
#define PDFSymbolChar_one 131
#define PDFSymbolChar_parenleft 132
#define PDFSymbolChar_parenright 133
#define PDFSymbolChar_parenlefttp 134
#define PDFSymbolChar_parenleftex 135
#define PDFSymbolChar_parenleftbt 136
#define PDFSymbolChar_parenrighttp 137
#define PDFSymbolChar_parenrightex 138
#define PDFSymbolChar_parenrightbt 139
#define PDFSymbolChar_partialdiff 140
#define PDFSymbolChar_percent 141
#define PDFSymbolChar_period 142
#define PDFSymbolChar_perpendicular 143
#define PDFSymbolChar_phi 144
#define PDFSymbolChar_phi1 145
#define PDFSymbolChar_pi 146
#define PDFSymbolChar_plus 147
#define PDFSymbolChar_plusminus 148
#define PDFSymbolChar_product 149
#define PDFSymbolChar_propersubset 150
#define PDFSymbolChar_propersuperset 151
#define PDFSymbolChar_proportional 152
#define PDFSymbolChar_psi 153
#define PDFSymbolChar_question 154
#define PDFSymbolChar_radical 155
#define PDFSymbolChar_radicalex 156
#define PDFSymbolChar_reflexsubset 157
#define PDFSymbolChar_reflexsuperset 158
#define PDFSymbolChar_registersans 159
#define PDFSymbolChar_registerserif 160
#define PDFSymbolChar_rho 161
#define PDFSymbolChar_second 162
#define PDFSymbolChar_semicolon 163
#define PDFSymbolChar_seven 164
#define PDFSymbolChar_sigma 165
#define PDFSymbolChar_sigma1 166
#define PDFSymbolChar_similar 167
#define PDFSymbolChar_six 168
#define PDFSymbolChar_slash 169
#define PDFSymbolChar_space 170
#define PDFSymbolChar_spade 171
#define PDFSymbolChar_suchthat 172
#define PDFSymbolChar_summation 173
#define PDFSymbolChar_tau 174
#define PDFSymbolChar_therefore 175
#define PDFSymbolChar_theta 176
#define PDFSymbolChar_theta1 177
#define PDFSymbolChar_three 178
#define PDFSymbolChar_trademarksans 179
#define PDFSymbolChar_trademarkserif 180
#define PDFSymbolChar_two 181
#define PDFSymbolChar_underscore 182
#define PDFSymbolChar_union 183
#define PDFSymbolChar_universal 184
#define PDFSymbolChar_upsilon 185
#define PDFSymbolChar_weierstrass 186
#define PDFSymbolChar_xi 187
#define PDFSymbolChar_zero 188
#define PDFSymbolChar_zeta 189

#define  PDFZapfDingbatsChar_NULL 0
#define  PDFZapfDingbatsChar_a1 1
#define  PDFZapfDingbatsChar_a10    2
#define  PDFZapfDingbatsChar_a100   3
#define  PDFZapfDingbatsChar_a101   4
#define  PDFZapfDingbatsChar_a102   5
#define  PDFZapfDingbatsChar_a103   6
#define  PDFZapfDingbatsChar_a104   7
#define  PDFZapfDingbatsChar_a105   8
#define  PDFZapfDingbatsChar_a106   9
#define  PDFZapfDingbatsChar_a107   10
#define  PDFZapfDingbatsChar_a108   11
#define  PDFZapfDingbatsChar_a109   12
#define  PDFZapfDingbatsChar_a11    13
#define  PDFZapfDingbatsChar_a110   14
#define  PDFZapfDingbatsChar_a111   15
#define  PDFZapfDingbatsChar_a112   16
#define  PDFZapfDingbatsChar_a117   17
#define  PDFZapfDingbatsChar_a118   18
#define  PDFZapfDingbatsChar_a119   19
#define  PDFZapfDingbatsChar_a12    20
#define  PDFZapfDingbatsChar_a120   21
#define  PDFZapfDingbatsChar_a121   22
#define  PDFZapfDingbatsChar_a122   23
#define  PDFZapfDingbatsChar_a123   24
#define  PDFZapfDingbatsChar_a124   25
#define  PDFZapfDingbatsChar_a125   26
#define  PDFZapfDingbatsChar_a126   27
#define  PDFZapfDingbatsChar_a127   28
#define  PDFZapfDingbatsChar_a128   29
#define  PDFZapfDingbatsChar_a129   30
#define  PDFZapfDingbatsChar_a13    31
#define  PDFZapfDingbatsChar_a130   32
#define  PDFZapfDingbatsChar_a131   33
#define  PDFZapfDingbatsChar_a132   34
#define  PDFZapfDingbatsChar_a133   35
#define  PDFZapfDingbatsChar_a134   36
#define  PDFZapfDingbatsChar_a135   37
#define  PDFZapfDingbatsChar_a136   38
#define  PDFZapfDingbatsChar_a137   39
#define  PDFZapfDingbatsChar_a138   40
#define  PDFZapfDingbatsChar_a139   41
#define  PDFZapfDingbatsChar_a14    42
#define  PDFZapfDingbatsChar_a140   43
#define  PDFZapfDingbatsChar_a141   44
#define  PDFZapfDingbatsChar_a142   45
#define  PDFZapfDingbatsChar_a143   46
#define  PDFZapfDingbatsChar_a144   47
#define  PDFZapfDingbatsChar_a145   48
#define  PDFZapfDingbatsChar_a146   49
#define  PDFZapfDingbatsChar_a147   50
#define  PDFZapfDingbatsChar_a148   51
#define  PDFZapfDingbatsChar_a149   52
#define  PDFZapfDingbatsChar_a15    53
#define  PDFZapfDingbatsChar_a150   54
#define  PDFZapfDingbatsChar_a151   55
#define  PDFZapfDingbatsChar_a152   56
#define  PDFZapfDingbatsChar_a153   57
#define  PDFZapfDingbatsChar_a154   58
#define  PDFZapfDingbatsChar_a155   59
#define  PDFZapfDingbatsChar_a156   60
#define  PDFZapfDingbatsChar_a157   61
#define  PDFZapfDingbatsChar_a158   62
#define  PDFZapfDingbatsChar_a159   63
#define  PDFZapfDingbatsChar_a16    64
#define  PDFZapfDingbatsChar_a160   65
#define  PDFZapfDingbatsChar_a161   66
#define  PDFZapfDingbatsChar_a162   67
#define  PDFZapfDingbatsChar_a163   68
#define  PDFZapfDingbatsChar_a164   69
#define  PDFZapfDingbatsChar_a165   70
#define  PDFZapfDingbatsChar_a166   71
#define  PDFZapfDingbatsChar_a167   72
#define  PDFZapfDingbatsChar_a168   73
#define  PDFZapfDingbatsChar_a169   74
#define  PDFZapfDingbatsChar_a17    75
#define  PDFZapfDingbatsChar_a170   76
#define  PDFZapfDingbatsChar_a171   77
#define  PDFZapfDingbatsChar_a172   78
#define  PDFZapfDingbatsChar_a173   79
#define  PDFZapfDingbatsChar_a174   80
#define  PDFZapfDingbatsChar_a175   81
#define  PDFZapfDingbatsChar_a176   82
#define  PDFZapfDingbatsChar_a177   83
#define  PDFZapfDingbatsChar_a178   84
#define  PDFZapfDingbatsChar_a179   85
#define  PDFZapfDingbatsChar_a18    86
#define  PDFZapfDingbatsChar_a180   87
#define  PDFZapfDingbatsChar_a181   88
#define  PDFZapfDingbatsChar_a182   89
#define  PDFZapfDingbatsChar_a183   90
#define  PDFZapfDingbatsChar_a184   91
#define  PDFZapfDingbatsChar_a185   92
#define  PDFZapfDingbatsChar_a186   93
#define  PDFZapfDingbatsChar_a187   94
#define  PDFZapfDingbatsChar_a188   95
#define  PDFZapfDingbatsChar_a189   96
#define  PDFZapfDingbatsChar_a19    97
#define  PDFZapfDingbatsChar_a190   98
#define  PDFZapfDingbatsChar_a191   99
#define  PDFZapfDingbatsChar_a192   100
#define  PDFZapfDingbatsChar_a193   101
#define  PDFZapfDingbatsChar_a194   102
#define  PDFZapfDingbatsChar_a195   103
#define  PDFZapfDingbatsChar_a196   104
#define  PDFZapfDingbatsChar_a197   105
#define  PDFZapfDingbatsChar_a198   106
#define  PDFZapfDingbatsChar_a199   107
#define  PDFZapfDingbatsChar_a2 108
#define  PDFZapfDingbatsChar_a20    109
#define  PDFZapfDingbatsChar_a200   110
#define  PDFZapfDingbatsChar_a201   111
#define  PDFZapfDingbatsChar_a202   112
#define  PDFZapfDingbatsChar_a203   113
#define  PDFZapfDingbatsChar_a204   114
#define  PDFZapfDingbatsChar_a21    115
#define  PDFZapfDingbatsChar_a22    116
#define  PDFZapfDingbatsChar_a23    117
#define  PDFZapfDingbatsChar_a24    118
#define  PDFZapfDingbatsChar_a25    119
#define  PDFZapfDingbatsChar_a26    120
#define  PDFZapfDingbatsChar_a27    121
#define  PDFZapfDingbatsChar_a28    122
#define  PDFZapfDingbatsChar_a29    123
#define  PDFZapfDingbatsChar_a3 124
#define  PDFZapfDingbatsChar_a30    125
#define  PDFZapfDingbatsChar_a31    126
#define  PDFZapfDingbatsChar_a32    127
#define  PDFZapfDingbatsChar_a33    128
#define  PDFZapfDingbatsChar_a34    129
#define  PDFZapfDingbatsChar_a35    130
#define  PDFZapfDingbatsChar_a36    131
#define  PDFZapfDingbatsChar_a37    132
#define  PDFZapfDingbatsChar_a38    133
#define  PDFZapfDingbatsChar_a39    134
#define  PDFZapfDingbatsChar_a4 135
#define  PDFZapfDingbatsChar_a40    136
#define  PDFZapfDingbatsChar_a41    137
#define  PDFZapfDingbatsChar_a42    138
#define  PDFZapfDingbatsChar_a43    139
#define  PDFZapfDingbatsChar_a44    140
#define  PDFZapfDingbatsChar_a45    141
#define  PDFZapfDingbatsChar_a46    142
#define  PDFZapfDingbatsChar_a47    143
#define  PDFZapfDingbatsChar_a48    144
#define  PDFZapfDingbatsChar_a49    145
#define  PDFZapfDingbatsChar_a5 146
#define  PDFZapfDingbatsChar_a50    147
#define  PDFZapfDingbatsChar_a51    148
#define  PDFZapfDingbatsChar_a52    149
#define  PDFZapfDingbatsChar_a53    150
#define  PDFZapfDingbatsChar_a54    151
#define  PDFZapfDingbatsChar_a55    152
#define  PDFZapfDingbatsChar_a56    153
#define  PDFZapfDingbatsChar_a57    154
#define  PDFZapfDingbatsChar_a58    155
#define  PDFZapfDingbatsChar_a59    156
#define  PDFZapfDingbatsChar_a6 157
#define  PDFZapfDingbatsChar_a60    158
#define  PDFZapfDingbatsChar_a61    159
#define  PDFZapfDingbatsChar_a62    160
#define  PDFZapfDingbatsChar_a63    161
#define  PDFZapfDingbatsChar_a64    162
#define  PDFZapfDingbatsChar_a65    163
#define  PDFZapfDingbatsChar_a66    164
#define  PDFZapfDingbatsChar_a67    165
#define  PDFZapfDingbatsChar_a68    166
#define  PDFZapfDingbatsChar_a69    167
#define  PDFZapfDingbatsChar_a7 168
#define  PDFZapfDingbatsChar_a70    169
#define  PDFZapfDingbatsChar_a71    170
#define  PDFZapfDingbatsChar_a72    171
#define  PDFZapfDingbatsChar_a73    172
#define  PDFZapfDingbatsChar_a74    173
#define  PDFZapfDingbatsChar_a75    174
#define  PDFZapfDingbatsChar_a76    175
#define  PDFZapfDingbatsChar_a77    176
#define  PDFZapfDingbatsChar_a78    177
#define  PDFZapfDingbatsChar_a79    178
#define  PDFZapfDingbatsChar_a8 179
#define  PDFZapfDingbatsChar_a81    180
#define  PDFZapfDingbatsChar_a82    181
#define  PDFZapfDingbatsChar_a83    182
#define  PDFZapfDingbatsChar_a84    183
#define  PDFZapfDingbatsChar_a9 184
#define  PDFZapfDingbatsChar_a97    185
#define  PDFZapfDingbatsChar_a98    186
#define  PDFZapfDingbatsChar_a99    187
#define  PDFZapfDingbatsChar_space  188


    


#ifdef __cplusplus
}
#endif

#endif /* #ifndef VSStdFont_H*/
