{

SYBREX SYSTEMS LIMITED
Copyright (C) 2005 - 2007 Sybrex Systems Ltd.
All rights reserved.

NOTICE: Sybrex permits you to use, modify, and distribute this file
in accordance with the terms of the Sybrex license agreement
accompanying it. If you have received this file from a source other
than Sybrex, then your use, modification, or distribution of it
requires the prior written permission of Sybrex.

}


{$ifdef DEBUGOFF}
{$D-,L-}
{$else}
{$D+,L+}
{$endif}
