#ifndef H_VERSYPDFJPEG
#define H_VERSYPDFJPEG

/* Short forms of external names for systems with brain-damaged linkers. */


#define jpeg_std_error                                  VersyPDF_jpeg_std_error
#define jpeg_CreateCompress                             VersyPDF_jpeg_CreateCompress
#define jpeg_CreateDecompress                           VersyPDF_jpeg_CreateDecompress
#define jpeg_destroy_compress                           VersyPDF_jpeg_destroy_compress
#define jpeg_destroy_decompress                         VersyPDF_jpeg_destroy_decompress
#define jpeg_stdio_dest                                 VersyPDF_jpeg_stdio_dest
#define jpeg_stdio_src                                  VersyPDF_jpeg_stdio_src
#define jpeg_set_defaults                               VersyPDF_jpeg_set_defaults
#define jpeg_set_colorspace                             VersyPDF_jpeg_set_colorspace
#define jpeg_default_colorspace                         VersyPDF_jpeg_default_colorspace
#define jpeg_set_quality                                VersyPDF_jpeg_set_quality
#define jpeg_set_linear_quality                         VersyPDF_jpeg_set_linear_quality
#define jpeg_add_quant_table                            VersyPDF_jpeg_add_quant_table
#define jpeg_quality_scaling                            VersyPDF_jpeg_quality_scaling
#define jpeg_simple_progression                         VersyPDF_jpeg_simple_progression
#define jpeg_suppress_tables                            VersyPDF_jpeg_suppress_tables
#define jpeg_alloc_quant_table                          VersyPDF_jpeg_alloc_quant_table
#define jpeg_alloc_huff_table                           VersyPDF_jpeg_alloc_huff_table
#define jpeg_start_compress                             VersyPDF_jpeg_start_compress
#define jpeg_write_scanlines                            VersyPDF_jpeg_write_scanlines
#define jpeg_finish_compress                            VersyPDF_jpeg_finish_compress
#define jpeg_write_raw_data                             VersyPDF_jpeg_write_raw_data
#define jpeg_write_marker                               VersyPDF_jpeg_write_marker
#define jpeg_write_m_header                             VersyPDF_jpeg_write_m_header
#define jpeg_write_m_byte                               VersyPDF_jpeg_write_m_byte
#define jpeg_write_tables                               VersyPDF_jpeg_write_tables
#define jpeg_read_header                                VersyPDF_jpeg_read_header
#define jpeg_start_decompress                           VersyPDF_jpeg_start_decompress
#define jpeg_read_scanlines                             VersyPDF_jpeg_read_scanlines
#define jpeg_finish_decompress                          VersyPDF_jpeg_finish_decompress
#define jpeg_read_raw_data                              VersyPDF_jpeg_read_raw_data
#define jpeg_has_multiple_scans                         VersyPDF_jpeg_has_multiple_scans
#define jpeg_start_output                               VersyPDF_jpeg_start_output
#define jpeg_finish_output                              VersyPDF_jpeg_finish_output
#define jpeg_input_complete                             VersyPDF_jpeg_input_complete
#define jpeg_new_colormap                               VersyPDF_jpeg_new_colormap
#define jpeg_consume_input                              VersyPDF_jpeg_consume_input
#define jpeg_calc_output_dimensions                     VersyPDF_jpeg_calc_output_dimensions
#define jpeg_save_markers                               VersyPDF_jpeg_save_markers
#define jpeg_set_marker_processor                       VersyPDF_jpeg_set_marker_processor
#define jpeg_read_coefficients                          VersyPDF_jpeg_read_coefficients
#define jpeg_write_coefficients                         VersyPDF_jpeg_write_coefficients
#define jpeg_copy_critical_parameters                   VersyPDF_jpeg_copy_critical_parameters
#define jpeg_abort_compress                             VersyPDF_jpeg_abort_compress
#define jpeg_abort_decompress                           VersyPDF_jpeg_abort_decompress
#define jpeg_abort                                      VersyPDF_jpeg_abort
#define jpeg_destroy                                    VersyPDF_jpeg_destroy
#define jpeg_resync_to_restart                          VersyPDF_jpeg_resync_to_restart
#define jpeg_reset_huff_decode				VersyPDF_jpeg_reset_huff_decode
#define jinit_compress_master           		VersyPDF_jinit_compress_master
#define jinit_c_master_control   		        VersyPDF_jinit_c_master_control
#define jinit_c_main_controller         		VersyPDF_jinit_c_main_controller
#define jinit_c_prep_controller         		VersyPDF_jinit_c_prep_controller
#define jinit_c_coef_controller         		VersyPDF_jinit_c_coef_controller
#define jinit_color_converter           VersyPDF_jinit_color_converter
#define jinit_downsampler               VersyPDF_jinit_downsampler
#define jinit_forward_dct               VersyPDF_jinit_forward_dct
#define jinit_huff_encoder              VersyPDF_jinit_huff_encoder
#define jinit_phuff_encoder             VersyPDF_jinit_phuff_encoder
#define jinit_marker_writer             VersyPDF_jinit_marker_writer
#define jinit_master_decompress         VersyPDF_jinit_master_decompress
#define jinit_d_main_controller         VersyPDF_jinit_d_main_controller
#define jinit_d_coef_controller         VersyPDF_jinit_d_coef_controller
#define jinit_d_post_controller         VersyPDF_jinit_d_post_controller
#define jinit_input_controller          VersyPDF_jinit_input_controller
#define jinit_marker_reader             VersyPDF_jinit_marker_reader
#define jinit_huff_decoder              VersyPDF_jinit_huff_decoder
#define jinit_phuff_decoder             VersyPDF_jinit_phuff_decoder
#define jinit_inverse_dct               VersyPDF_jinit_inverse_dct
#define jinit_upsampler                 VersyPDF_jinit_upsampler
#define jinit_color_deconverter         VersyPDF_jinit_color_deconverter
#define jinit_1pass_quantizer           VersyPDF_jinit_1pass_quantizer
#define jinit_2pass_quantizer           VersyPDF_jinit_2pass_quantizer
#define jinit_merged_upsampler          VersyPDF_jinit_merged_upsampler
#define jinit_memory_mgr                VersyPDF_jinit_memory_mgr
#define jdiv_round_up                   VersyPDF_jdiv_round_up
#define jround_up                       VersyPDF_jround_up
#define jcopy_sample_rows               VersyPDF_jcopy_sample_rows
#define jcopy_block_row                 VersyPDF_jcopy_block_row
#define jzero_far                       VersyPDF_jzero_far
#define jpeg_zigzag_order               VersyPDF_jpeg_zigzag_order
#define jpeg_natural_order              VersyPDF_jpeg_natural_order
#define jpeg_make_c_derived_tbl VersyPDF_jpeg_make_c_derived_tbl
#define jpeg_gen_optimal_table  VersyPDF_jpeg_gen_optimal_table
#define jpeg_fdct_islow           VersyPDF_jpeg_fdct_islow
#define jpeg_fdct_ifast           VersyPDF_jpeg_fdct_ifast
#define jpeg_fdct_float           VersyPDF_jpeg_fdct_float
#define jpeg_idct_islow           VersyPDF_jpeg_idct_islow
#define jpeg_idct_ifast           VersyPDF_jpeg_idct_ifast
#define jpeg_idct_float           VersyPDF_jpeg_idct_float
#define jpeg_idct_4x4             VersyPDF_jpeg_idct_4x4
#define jpeg_idct_2x2             VersyPDF_jpeg_idct_2x2
#define jpeg_idct_1x1             VersyPDF_jpeg_idct_1x1
#define jpeg_make_d_derived_tbl         VersyPDF_jpeg_make_d_derived_tbl
#define jpeg_fill_bit_buffer            VersyPDF_jpeg_fill_bit_buffer
#define jpeg_huff_decode                VersyPDF_jpeg_huff_decode
#define jpeg_std_message_table	VersyPDF_jpeg_std_message_table
#define jpeg_get_small            VersyPDF_jpeg_get_small
#define jpeg_free_small           VersyPDF_jjpeg_free_small
#define jpeg_get_large            VersyPDF_jjpeg_get_large
#define jpeg_free_large           VersyPDF_jjpeg_free_large
#define jpeg_mem_available        VersyPDF_jjpeg_mem_available
#define jpeg_open_backing_store   VersyPDF_jjpeg_open_backing_store
#define jpeg_mem_init             VersyPDF_jjpeg_mem_init
#define jpeg_mem_term             VersyPDF_jjpeg_mem_term
#define jpeg_std_message_table	VersyPDF_jpeg_std_message_table


#endif