#ifndef _VSFREETYPE_H
#define _VSFREETYPE_H


/*********************************************************************

SYBREX SYSTEMS INCORPORATED
Copyright (C) 2005 Sybrex Systems Incorporated
All rights reserved.

NOTICE: Sybrex permits you to use, modify, and distribute this file
in accordance with the terms of the Sybrex license agreement
accompanying it. If you have received this file from a source other
than Sybrex, then your use, modification, or distribution of it
requires the prior written permission of Sybrex.

----------------------------------------------------------------------
VSFreeType.h
*********************************************************************/

#define	FT_Init_FreeType		VersyPDF_FT_Init_FreeType
#define	FT_New_Memory			VersyPDF_FT_New_Memory
#define	ft_alloc				VersyPDF_ft_alloc
#define	ft_free					VersyPDF_ft_free
#define	ft_realloc				VersyPDF_ft_realloc
#define	FT_New_Library			VersyPDF_FT_New_Library
#define	FT_Add_Default_Modules	VersyPDF_FT_Add_Default_Modules
#define	FT_Add_Module			VersyPDF_FT_Add_Module
#define	FT_Remove_Module		VersyPDF_FT_Remove_Module
#define	Destroy_Module			VersyPDF_Destroy_Module	
#define	ft_add_renderer			VersyPDF_ft_add_renderer
#define	FT_List_Add				VersyPDF_FT_List_Add		
#define	ft_set_current_renderer VersyPDF_ft_set_current_renderer 
#define	FT_Lookup_Renderer		VersyPDF_FT_Lookup_Renderer	
#define	FT_GlyphLoader_New		VersyPDF_FT_GlyphLoader_New	
#define	FT_GlyphLoader_Done		VersyPDF_FT_GlyphLoader_Done
#define	FT_GlyphLoader_Reset	VersyPDF_FT_GlyphLoader_Reset
#define	FT_GlyphLoader_Rewind	VersyPDF_FT_GlyphLoader_Rewind 
#define	FT_New_Memory_Face		VersyPDF_FT_New_Memory_Face
#define	FT_Open_Face			VersyPDF_FT_Open_Face
#define	FT_Stream_New			VersyPDF_FT_Stream_New
#define	FT_Stream_OpenMemory	VersyPDF_FT_Stream_OpenMemory
#define	FT_Stream_Open			VersyPDF_FT_Stream_Open
#define	open_face				VersyPDF_open_face
#define	FT_Stream_Free			VersyPDF_FT_Stream_Free
#define	FT_Stream_Close			VersyPDF_FT_Stream_Close
#define	FT_New_GlyphSlot		VersyPDF_FT_New_GlyphSlot
#define	ft_glyphslot_init		VersyPDF_ft_glyphslot_init
#define	ft_glyphslot_done		VersyPDF_ft_glyphslot_done
#define	FT_New_Size				VersyPDF_FT_New_Size
#define	FT_Done_Face			VersyPDF_FT_Done_Face
#define	FT_List_Find			VersyPDF_FT_List_Find
#define	FT_List_Remove			VersyPDF_FT_List_Remove
#define	destroy_face			VersyPDF_destroy_face
#define	FT_Done_GlyphSlot		VersyPDF_FT_Done_GlyphSlot
#define	FT_List_Finalize		VersyPDF_FT_List_Finalize
#define	FT_Get_Char_Index		VersyPDF_FT_Get_Char_Index
#define	FT_Load_Glyph			VersyPDF_FT_Load_Glyph
#define	ft_glyphslot_clear		VersyPDF_ft_glyphslot_clear
#define	ft_glyphslot_free_bitmap	VersyPDF_ft_glyphslot_free_bitmap
#define	FT_Outline_Check		VersyPDF_FT_Outline_Check
#define	FT_MulDiv				VersyPDF_FT_MulDiv
#define	FT_Add64				VersyPDF_FT_Add64
#define	ft_multo64				VersyPDF_ft_multo64
#define	ft_div64by32			VersyPDF_ft_div64by32
#define	ft_lookup_glyph_renderer	VersyPDF_ft_lookup_glyph_renderer
#define	FT_Vector_Transform		VersyPDF_FT_Vector_Transform
#define	FT_MulFix				VersyPDF_FT_MulFix
#define	FT_Render_Glyph			VersyPDF_FT_Render_Glyph										
#define	FT_Render_Glyph_Internal	VersyPDF_FT_Render_Glyph_Internal	
#define	FT_Done_Face			VersyPDF_FT_Done_Face
#define	FT_Done_FreeType		VersyPDF_FT_Done_FreeType
#define	FT_Done_Library			VersyPDF_FT_Done_Library
#define	FT_Done_Memory			VersyPDF_FT_Done_Memory
#define	cid_load_glyph			vspd_cid_load_glyph
#define	cid_get_offset			VersyPDF_cid_get_offset
#define	cid_load_keyword		VersyPDF_cid_load_keyword
#define	parse_font_matrix		VersyPDF_parse_font_matrix
#define	parse_fd_array			VersyPDF_parse_fd_array
#define	cid_parse_dict			VersyPDF_cid_parse_dict
#define	cid_read_subrs			VersyPDF_cid_read_subrs
#define	cid_hex_to_binary		VersyPDF_cid_hex_to_binary
#define	cid_face_open			VersyPDF_cid_face_open
#define	cid_slot_done			VersyPDF_cid_slot_done
#define	cid_slot_init			VersyPDF_cid_slot_init
#define	cid_size_get_globals_funcs	VersyPDF_cid_size_get_globals_funcs
#define	cid_size_done			VersyPDF_cid_size_done
#define	cid_size_init			VersyPDF_cid_size_init
#define	cid_size_reset			VersyPDF_cid_size_reset
#define	cid_point_size_reset	VersyPDF_cid_point_size_reset
#define	cid_face_done			VersyPDF_cid_face_done
#define	cid_face_init			VersyPDF_cid_face_init
#define	cid_driver_init			VersyPDF_cid_driver_init
#define	cid_driver_done			VersyPDF_cid_driver_done
#define	cid_parser_new			VersyPDF_cid_parser_new
#define	cid_parser_done			VersyPDF_cid_parser_done
#define	cid_get_interface		VersyPDF_cid_get_interface
#define	cid_get_postscript_name	VersyPDF_cid_get_postscript_name
#define	cid_ps_get_font_info	VersyPDF_cid_ps_get_font_info
#define	FT_Access_Frame			VersyPDF_FT_Access_Frame
#define	FT_Extract_Frame		VersyPDF_FT_Extract_Frame
#define	FT_Forget_Frame			VersyPDF_FT_Forget_Frame
#define	FT_New_Memory_Stream	VersyPDF_FT_New_Memory_Stream
#define	FT_Read_Stream			VersyPDF_FT_Read_Stream
#define	FT_Read_Stream_At		VersyPDF_FT_Read_Stream_At
#define	FT_Release_Frame		VersyPDF_FT_Release_Frame
#define	FT_Seek_Stream			VersyPDF_FT_Seek_Stream
#define	FT_Skip_Stream			VersyPDF_FT_Skip_Stream
#define	BBox_Conic_Check		VersyPDF_BBox_Conic_Check
#define	BBox_Conic_To			VersyPDF_BBox_Conic_To
#define	BBox_Cubic_Check		VersyPDF_BBox_Cubic_Check
#define	BBox_Move_To			VersyPDF_BBox_Move_To
#define	FT_Online_Get_BBox		VersyPDF_FT_Online_Get_BBox
#define	FT_Get_BDF_Charset_ID	VersyPDF_FT_Get_BDF_Charset_ID
#define	ft_bitmap_assure_buffer	VersyPDF_ft_bitmap_assure_buffer
#define	FT_Bitmap_Convert		VersyPDF_FT_Bitmap_Convert
#define	FT_Bitmap_Done			VersyPDF_FT_Bitmap_Done
#define	FT_Bitmap_Copy			VersyPDF_FT_Bitmap_Copy
#define	FT_Bitmap_Embolden		VersyPDF_FT_Bitmap_Embolden
#define	FT_Bitmap_New			VersyPDF_FT_Bitmap_New
#define	FT_CeilFix				VersyPDF_FT_CeilFix
#define	FT_Div64by32			VersyPDF_FT_Div64by32
#define	FT_DivFix				VersyPDF_FT_DivFix
#define	FT_FloorFix				VersyPDF_FT_FloorFix
#define	FT_MulTo64				VersyPDF_FT_MulTo64
#define	FT_RoundFix				VersyPDF_FT_RoundFix
#define	FT_Sqrt32				VersyPDF_FT_Sqrt32
#define	FT_SqrtFixed			VersyPDF_FT_SqrtFixed
#define	ft_debug_init			VersyPDF_ft_debug_init
#define	FT_Trace_Get_Count		VersyPDF_FT_Trace_Get_Count
#define	FT_Trace_Get_Name		VersyPDF_FT_Trace_Get_Name
#define	FT_Glyph_Loader_Add		VersyPDF_FT_Glyph_Loader_Add
#define	FT_Glyph_Loader_Adjus_Points	VersyPDF_FT_Glyph_Loader_Adjus_Points
#define	FT_Glyph_Loader_Adjus_Subglyphs	VersyPDF_FT_Glyph_Loader_Adjus_Subglyphs
#define	FT_Glyph_Loader_CheckPoints	VersyPDF_FT_Glyph_Loader_CheckPoints
#define	FT_Glyph_Loader_CheckSubGlyphs	VersyPDF_FT_Glyph_Loader_CheckSubGlyphs
#define	FT_Glyph_Loader_CopyPoints	VersyPDF_FT_Glyph_Loader_CopyPoints
#define	FT_Glyph_Loader_CreateExtra	VersyPDF_FT_Glyph_Loader_CreateExtra
#define	FT_Glyph_Loader_Prepare		VersyPDF_FT_Glyph_Loader_Prepare
#define	ft_bitmap_glyph_class		VersyPDF_ft_bitmap_glyph_class
#define	ft_bitmap_glyph_bbox	VersyPDF_ft_bitmap_glyph_bbox
#define	ft_bitmap_glyph_copy	VersyPDF_ft_bitmap_glyph_copy
#define	ft_bitmap_glyph_done	VersyPDF_ft_bitmap_glyph_done
#define	ft_bitmap_glyph_init	VersyPDF_ft_bitmap_glyph_init
#define	FT_Done_Glyph			VersyPDF_FT_Done_Glyph
#define	FT_Get_Glyph			VersyPDF_FT_Get_Glyphv
#define	FT_Glyph_Copy			VersyPDF_FT_Glyph_Copy
#define	FT_Glyph_Get_CBox		VersyPDF_FT_Glyph_Get_CBox
#define	FT_Glyph_To_Bitmap		VersyPDF_FT_Glyph_To_Bitmap
#define	FT_Glyph_Transform		VersyPDF_FT_Glyph_Transform
#define	FT_Matrix_Invert		VersyPDF_FT_Matrix_Invert
#define	FT_Matrix_Multiply		VersyPDF_FT_Matrix_Multiply
#define	ft_new_glyph			VersyPDF_ft_new_glyph
#define	ft_outline_glyph_bbox	VersyPDF_ft_outline_glyph_bbox
#define	ft_outline_glyph_done	VersyPDF_ft_outline_glyph_done
#define	ft_outline_glyph_init	VersyPDF_ft_outline_glyph_init
#define	ft_outline_glyph_prepare	VersyPDF_ft_outline_glyph_prepare
#define	ft_outline_glyph_transform	VersyPDF_ft_outline_glyph_transform
#define	FT_Stream_OpenLZW		VersyPDF_FT_Stream_OpenLZW
#define	FT_Get_MM_Var			VersyPDF_FT_Get_MM_Var
#define	FT_Get_Multi_Master		VersyPDF_FT_Get_Multi_Master
#define	FT_Get_MM_Blend_Coordinates	VersyPDF_FT_Get_MM_Blend_Coordinates
#define	FT_Get_MM_Design_Coordinates	VersyPDF_FT_Get_MM_Design_Coordinates
#define	FT_Get_Var_Blend_Coordinates	VersyPDF_FT_Get_Var_Blend_Coordinates
#define	FT_Get_Var_Design_Coordinates	VersyPDF_FT_Get_Var_Design_Coordinates
#define	ft_cmap_done_internal			VersyPDF_ft_cmap_done_internal
#define	destroy_charmaps		VersyPDF_destroy_charmaps
#define	Destroy_Driver			VersyPDF_Destroy_Driver
#define	destroy_size			VersyPDF_destroy_size
#define	find_unicode_charmap	VersyPDF_find_unicode_charmap
#define	FT_Activate_Size		VersyPDF_FT_Activate_Size
#define	FT_Attach_File			VersyPDF_FT_Attach_File
#define	FT_Attach_Stream		VersyPDF_FT_Attach_Stream
#define	FT_CMap_Done			VersyPDF_FT_CMap_Done
#define	FT_CMap_New				VersyPDF_FT_CMap_New
#define	FT_Done_Size			VersyPDF_FT_Done_Size
#define	FT_Get_CMap_Language_ID	VersyPDF_FT_Get_CMap_Language_ID
#define	FT_Get_First_Char		VersyPDF_FT_Get_First_Char
#define	FT_Get_Glyph_Name		VersyPDF_FT_Get_Glyph_Name
#define	FT_Get_Kerning			VersyPDF_FT_Get_Kerning
#define	FT_Get_Module			VersyPDF_FT_Get_Module
#define	FT_Get_Module_Interface	VersyPDF_FT_Get_Module_Interface
#define	FT_Get_Name_Index		VersyPDF_FT_Get_Name_Index
#define	FT_Get_Next_Char		VersyPDF_FT_Get_Next_Char
#define	FT_Get_Postscript_Name	VersyPDF_FT_Get_Postscript_Name
#define	FT_Get_Renderer			VersyPDF_FT_Get_Renderer
#define	ft_glyphslot_alloc_bitmap	VersyPDF_ft_glyphslot_alloc_bitmap
#define	ft_glyphslot_set_bitmap	VersyPDF_ft_glyphslot_set_bitmap
#define	FT_Library_Version		VersyPDF_FT_Library_Version
#define	FT_Load_Char			VersyPDF_FT_Load_Char
#define	FT_Load_Sfnt_Table		VersyPDF_FT_Load_Sfnt_Table
#define	ft_module_get_service	VersyPDF_ft_module_get_service
#define	FT_New_Face				VersyPDF_FT_New_Face
#define	ft_recompute_scaled_metrics	VersyPDF_ft_recompute_scaled_metrics
#define	FT_Select_Charmap		VersyPDF_FT_Select_Charmap
#define	ft_service_list_lookup	VersyPDF_ft_service_list_lookup
#define	FT_Set_Char_Size		VersyPDF_FT_Set_Char_Size
#define	FT_Set_Charmap			VersyPDF_FT_Set_Charmap
#define	FT_Set_Debug_Hook		VersyPDF_FT_Set_Debug_Hook
#define	FT_Set_Pixel_Sizes		VersyPDF_FT_Set_Pixel_Sizes
#define	FT_Set_Renderer			VersyPDF_FT_Set_Renderer
#define	FT_Set_Transform		VersyPDF_FT_Set_Transform
#define	FT_Sfnt_Table_Info		VersyPDF_FT_Sfnt_Table_Info
#define	ft_validator_error		VersyPDF_ft_validator_error
#define	ft_validator_init		VersyPDF_ft_validator_init
#define	ft_validator_run		VersyPDF_ft_validator_run
#define	FT_OpenType_Validate	VersyPDF_FT_OpenType_Validate
#define	FT_Outline_Copy			VersyPDF_FT_Outline_Copy
#define	FT_Outline_Decompose	VersyPDF_FT_Outline_Decompose
#define	FT_Outline_Done			VersyPDF_FT_Outline_Done
#define	FT_Outline_Done_Internal	VersyPDF_FT_Outline_Done_Internal
#define	FT_Outline_Embolden		VersyPDF_FT_Outline_Embolden
#define	FT_Outline_Get_Bitmap	VersyPDF_FT_Outline_Get_Bitmap
#define	FT_Outline_Get_CBox		VersyPDF_FT_Outline_Get_CBox
#define	FT_Outline_Get_Orientation	VersyPDF_FT_Outline_Get_Orientation
#define	FT_Outline_New			VersyPDF_FT_Outline_New
#define	FT_Outline_New_Internal	VersyPDF_FT_Outline_New_Internal
#define	FT_Outline_Render		VersyPDF_FT_Outline_Render
#define	FT_Outline_Reverse		VersyPDF_FT_Outline_Reverse
#define	FT_Outline_Transform	VersyPDF_FT_Outline_Transform
#define	FT_Outline_Translate	VersyPDF_FT_Outline_Translate
#define	ft_pfr_check			VersyPDF_ft_pfr_check
#define	FT_Get_PFR_Advance		VersyPDF_FT_Get_PFR_Advance
#define	FT_Get_PFR_Metrics		VersyPDF_FT_Get_PFR_Metrics
#define	FT_Get_PFR_Kerning		VersyPDF_FT_Get_PFR_Kerning
#define	FT_Raccess_Get_HeaderInfo	VersyPDF_FT_Raccess_Get_HeaderInfo
#define	FT_Raccess_Get_DataOffsets	VersyPDF_FT_Raccess_Get_DataOffsets
#define	FT_Raccess_Guess		VersyPDF_FT_Raccess_Guess
#define	raccess_guess_apple_double	VersyPDF_raccess_guess_apple_double
#define	raccess_guess_apple_single	VersyPDF_raccess_guess_apple_single
#define	raccess_guess_darwin_hfsplus	VersyPDF_raccess_guess_darwin_hfsplus
#define	raccess_guess_darwin_ufs_export	VersyPDF_raccess_guess_darwin_ufs_export
#define	raccess_guess_vfat		VersyPDF_raccess_guess_vfat
#define	raccess_guess_linux_cap	VersyPDF_raccess_guess_linux_cap
#define	raccess_guess_linux_double	VersyPDF_raccess_guess_linux_double
#define	raccess_guess_linux_netatalk	VersyPDF_raccess_guess_linux_netatalk
#define	raccess_guess_apple_generic	VersyPDF_raccess_guess_apple_generic
#define	raccess_guess_linux_double_from_file_name	VersyPDF_raccess_guess_linux_double_from_file_name
#define	raccess_make_file_name	VersyPDF_raccess_make_file_name
#define	FT_Stream_EnterFrame	VersyPDF_FT_Stream_EnterFrame
#define	FT_Stream_ExitFrame		VersyPDF_FT_Stream_ExitFrame
#define	FT_Stream_ExtractFrame	VersyPDF_FT_Stream_ExtractFrame
#define	FT_Stream_GetChar		VersyPDF_FT_Stream_GetChar
#define	FT_Stream_GetLong		VersyPDF_FT_Stream_GetLong
#define	FT_Stream_GetLongLE		VersyPDF_FT_Stream_GetLongLE
#define	FT_Stream_GetOffset		VersyPDF_FT_Stream_GetOffset
#define	FT_Stream_GetShort		VersyPDF_FT_Stream_GetShort
#define	FT_Stream_GetShortLE	VersyPDF_FT_Stream_GetShortLE
#define	FT_Stream_Pos			VersyPDF_FT_Stream_Pos
#define	FT_Stream_Read			VersyPDF_FT_Stream_Read
#define	FT_Stream_ReadAt		VersyPDF_FT_Stream_ReadAt
#define	FT_Stream_ReadChar		VersyPDF_FT_Stream_ReadChar
#define	FT_Stream_ReadFields	VersyPDF_FT_Stream_ReadFields
#define	FT_Stream_ReadLong		VersyPDF_FT_Stream_ReadLong
#define	FT_Stream_ReadLongLE	VersyPDF_FT_Stream_ReadLongLE
#define	FT_Stream_ReadOffset	VersyPDF_FT_Stream_ReadOffset
#define	FT_Stream_ReadShort		VersyPDF_FT_Stream_ReadShort
#define	FT_Stream_ReadShortLE	VersyPDF_FT_Stream_ReadShortLE
#define	FT_Stream_ReleaseFrame	VersyPDF_FT_Stream_ReleaseFrame
#define	FT_Stream_Seek			VersyPDF_FT_Stream_Seek
#define	FT_Stream_Skip			VersyPDF_FT_Stream_Skip
#define	FT_Stream_TryRead		VersyPDF_FT_Stream_TryRead
#define	ft_conic_split			VersyPDF_ft_conic_split
#define	ft_conic_is_small_enough	VersyPDF_ft_conic_is_small_enough
#define	ft_cubic_split			VersyPDF_ft_cubic_split
#define	ft_cubic_is_small_enough	VersyPDF_ft_cubic_is_small_enough
#define	FT_Glyph_Stroke			VersyPDF_FT_Glyph_Stroke
#define	FT_Glyph_StrokeBorder	VersyPDF_FT_Glyph_StrokeBorder
#define	FT_Outline_GetInsideBorder	VersyPDF_FT_Outline_GetInsideBorder
#define	FT_Outline_GetOutsideBorder	VersyPDF_FT_Outline_GetOutsideBorder
#define	ft_pos_abs					VersyPDF_ft_pos_abs
#define	ft_stroke_border_arcto		VersyPDF_ft_stroke_border_arcto
#define	ft_stroke_border_close		VersyPDF_ft_stroke_border_close
#define	ft_stroke_border_conicto	VersyPDF_ft_stroke_border_conicto
#define	ft_stroke_border_cubicto	VersyPDF_ft_stroke_border_cubicto
#define	ft_stroke_border_done		VersyPDF_ft_stroke_border_done
#define	ft_stroke_border_init		VersyPDF_ft_stroke_border_init
#define	ft_stroke_border_lineto		VersyPDF_ft_stroke_border_lineto
#define	ft_stroke_border_moveto		VersyPDF_ft_stroke_border_moveto
#define	ft_stroke_border_reset		VersyPDF_ft_stroke_border_reset
#define	ft_stroker_add_reverse_left	VersyPDF_ft_stroker_add_reverse_left
#define	ft_stroker_arcto			VersyPDF_ft_stroker_arcto
#define	ft_stroker_cap				VersyPDF_ft_stroker_cap
#define	FT_Stroker_BeginSubPath		VersyPDF_FT_Stroker_BeginSubPath
#define	FT_Stroker_ConicTo			VersyPDF_FT_Stroker_ConicTo
#define	FT_Stroker_CubicTo			VersyPDF_FT_Stroker_CubicTo
#define	FT_Stroker_Done				VersyPDF_FT_Stroker_Done
#define	FT_Stroker_EndSubPath		VersyPDF_FT_Stroker_EndSubPath
#define	FT_Stroker_Export			VersyPDF_FT_Stroker_Export
#define	FT_Stroker_ExportBorder		VersyPDF_FT_Stroker_ExportBorder
#define	FT_Stroker_GetBorderCounts	VersyPDF_FT_Stroker_GetBorderCounts
#define	FT_Stroker_GetCounts		VersyPDF_FT_Stroker_GetCounts
#define	ft_stroker_inside			VersyPDF_ft_stroker_inside
#define	FT_Stroker_LineTo			VersyPDF_FT_Stroker_LineTo
#define	FT_Stroker_New				VersyPDF_FT_Stroker_New
#define	ft_stroker_outside			VersyPDF_ft_stroker_outside
#define	FT_Stroker_ParseOutline		VersyPDF_FT_Stroker_ParseOutline
#define	ft_stroker_process_corner	VersyPDF_ft_stroker_process_corner
#define	FT_Stroker_Rewind			VersyPDF_FT_Stroker_Rewind
#define	FT_Stroker_Set				VersyPDF_FT_Stroker_Set
#define	ft_stroker_subpath_start	VersyPDF_ft_stroker_subpath_start
#define	FT_GlyphSlot_Embolden	VersyPDF_FT_GlyphSlot_Embolden
#define	FT_GlyphSlot_Oblique	VersyPDF_FT_GlyphSlot_Oblique
#define	ft_ansi_stream_close	VersyPDF_ft_ansi_stream_close
#define	ft_ansi_stream_io		VersyPDF_ft_ansi_stream_io
#define	FT_Angle_Diff		VersyPDF_FT_Angle_Diff
#define	FT_Atan2			VersyPDF_FT_Atan2
#define	FT_Cos				VersyPDF_FT_Cos
#define	FT_Sin				VersyPDF_FT_Sin
#define	FT_Tan				VersyPDF_FT_Tan
#define	ft_trig_downscale	VersyPDF_ft_trig_downscale
#define	ft_trig_prenorm		VersyPDF_ft_trig_prenorm
#define	ft_trig_pseudo_polarize	VersyPDF_ft_trig_pseudo_polarize
#define	ft_trig_pseudo_rotate	VersyPDF_ft_trig_pseudo_rotate
#define	FT_Vector_From_Polar	VersyPDF_FT_Vector_From_Polar
#define	FT_Vector_Length	VersyPDF_FT_Vector_Length
#define	FT_Vector_Polarize	VersyPDF_FT_Vector_Polarize
#define	FT_Vector_Rotate	VersyPDF_FT_Vector_Rotate
#define	FT_Vector_Unit		VersyPDF_FT_Vector_Unit
#define	FT_Has_PS_Glyph_Names	VersyPDF_FT_Has_PS_Glyph_Names
#define	FT_Get_PS_Font_Info		VersyPDF_FT_Get_PS_Font_Info
#define	FT_Get_PS_Font_Private	VersyPDF_FT_Get_PS_Font_Private
#define	FT_Alloc			VersyPDF_FT_Alloc
#define	FT_Free				VersyPDF_FT_Free
#define	ft_highpow2			VersyPDF_ft_highpow2
#define	FT_List_Insert		VersyPDF_FT_List_Insert
#define	FT_List_Iterate		VersyPDF_FT_List_Iterate
#define	FT_List_Up			VersyPDF_FT_List_Up
#define	FT_QAlloc			VersyPDF_FT_QAlloc
#define	FT_QRealloc			VersyPDF_FT_QRealloc
#define	FT_Realloc			VersyPDF_FT_Realloc
#define	ps_hints_apply		VersyPDF_ps_hints_apply
#define	psh_compute_dir		VersyPDF_psh_compute_dir
#define	psh_dimension_quantize_len		VersyPDF_psh_dimension_quantize_len
#define	psh_glyph_compute_extrema		VersyPDF_psh_glyph_compute_extrema
#define	psh_glyph_compute_inflections	VersyPDF_psh_glyph_compute_inflections
#define	psh_glyph_done					VersyPDF_psh_glyph_done
#define	psh_glyph_find_blue_points		VersyPDF_psh_glyph_find_blue_points
#define	psh_glyph_find_strong_points	VersyPDF_psh_glyph_find_strong_points
#define	psh_glyph_init						VersyPDF_psh_glyph_init
#define	psh_glyph_interpolate_normal_points	VersyPDF_psh_glyph_interpolate_normal_points
#define	psh_glyph_interpolate_strong_points	VersyPDF_psh_glyph_interpolate_strong_points
#define	psh_glyph_interpolate_other_points	VersyPDF_psh_glyph_interpolate_other_points
#define	psh_glyph_save_points	VersyPDF_psh_glyph_save_points
#define	psh_hint_align			VersyPDF_psh_hint_align
#define	psh_hint_overlap		VersyPDF_psh_hint_overlap
#define	psh_hint_snap_stem_side_delta	VersyPDF_psh_hint_snap_stem_side_delta
#define	psh_hint_table_activate_mask	VersyPDF_psh_hint_table_activate_mask
#define	psh_hint_table_align_hints		VersyPDF_psh_hint_table_align_hints
#define	psh_hint_table_deactivate		VersyPDF_psh_hint_table_deactivate
#define	psh_hint_table_done				VersyPDF_psh_hint_table_done
#define	psh_hint_table_find_strong_point	VersyPDF_psh_hint_table_find_strong_point
#define	psh_hint_table_init			VersyPDF_psh_hint_table_init
#define	psh_hint_table_record		VersyPDF_psh_hint_table_record
#define	psh_hint_table_record_mask	VersyPDF_psh_hint_table_record_mask
#define	psh_blues_scale_zones	VersyPDF_psh_blues_scale_zones
#define	psh_blues_set_zones		VersyPDF_psh_blues_set_zones
#define	psh_blues_set_zones_0	VersyPDF_psh_blues_set_zones_0
#define	psh_blues_snap_stem		VersyPDF_psh_blues_snap_stem
#define	psh_globals_destroy		VersyPDF_psh_globals_destroy
#define	psh_globals_funcs_init	VersyPDF_psh_globals_funcs_init
#define	psh_globals_new			VersyPDF_psh_globals_new
#define	psh_globals_scale_widths	VersyPDF_psh_globals_scale_widths
#define	psh_globals_set_scale	VersyPDF_psh_globals_set_scale
#define	ps_hinter_done			VersyPDF_ps_hinter_done
#define	ps_hinter_init			VersyPDF_ps_hinter_init
#define	pshinter_get_globals_funcs	VersyPDF_pshinter_get_globals_funcs
#define	pshinter_get_t1_funcs	VersyPDF_pshinter_get_t1_funcs
#define	pshinter_get_t2_funcs	VersyPDF_pshinter_get_t2_funcs
#define	ps_dimension_add_counter	VersyPDF_ps_dimension_add_counter
#define	ps_dimension_add_t1stem		VersyPDF_ps_dimension_add_t1stem
#define	ps_dimension_done			VersyPDF_ps_dimension_done
#define	ps_dimension_end			VersyPDF_ps_dimension_end
#define	ps_dimension_end_mask		VersyPDF_ps_dimension_end_mask
#define	ps_dimension_init			VersyPDF_ps_dimension_init
#define	ps_dimension_reset_mask		VersyPDF_ps_dimension_reset_mask
#define	ps_dimension_set_mask_bit	VersyPDF_ps_dimension_set_mask_bit
#define	ps_hint_table_alloc			VersyPDF_ps_hint_table_alloc
#define	ps_hint_table_done			VersyPDF_ps_hint_table_done
#define	ps_hint_table_ensure		VersyPDF_ps_hint_table_ensure
#define	ps_hints_close				VersyPDF_ps_hints_close
#define	ps_hints_done				VersyPDF_ps_hints_done
#define	ps_hints_init				VersyPDF_ps_hints_init
#define	ps_hints_open				VersyPDF_ps_hints_open
#define	ps_hints_stem				VersyPDF_ps_hints_stem
#define	ps_hints_t1reset			VersyPDF_ps_hints_t1reset
#define	ps_hints_t1stem3			VersyPDF_ps_hints_t1stem3
#define	ps_hints_t2counter			VersyPDF_ps_hints_t2counter
#define	ps_hints_t2mask				VersyPDF_ps_hints_t2mask
#define	ps_mask_done				VersyPDF_ps_mask_done
#define	ps_mask_clear_bit			VersyPDF_ps_mask_clear_bit
#define	ps_mask_ensure				VersyPDF_ps_mask_ensure
#define	ps_mask_set_bit				VersyPDF_ps_mask_set_bit
#define	ps_mask_table_done			VersyPDF_ps_mask_table_done
#define	ps_mask_table_alloc			VersyPDF_ps_mask_table_alloc			
#define	ps_mask_table_ensure		VersyPDF_ps_mask_table_ensure
#define	ps_mask_table_last			VersyPDF_ps_mask_table_last
#define	ps_mask_table_merge			VersyPDF_ps_mask_table_merge
#define	ps_mask_table_merge_all		VersyPDF_ps_mask_table_merge_all
#define	ps_mask_table_set_bits		VersyPDF_ps_mask_table_set_bits
#define	ps_mask_table_test_intersect	VersyPDF_ps_mask_table_test_intersect
#define	ps_mask_test_bit			VersyPDF_ps_mask_test_bit
#define	t1_hints_funcs_init			VersyPDF_t1_hints_funcs_init
#define	t1_hints_open				VersyPDF_t1_hints_open
#define	t1_hints_stem				VersyPDF_t1_hints_stem
#define	t2_hints_funcs_init			VersyPDF_t2_hints_funcs_init
#define	t2_hints_open				VersyPDF_t2_hints_open
#define	t2_hints_stems				VersyPDF_t2_hints_stems
#define	compare_uni_maps			VersyPDF_compare_uni_maps
#define	ps_get_macintosh_name		VersyPDF_ps_get_macintosh_name
#define	ps_get_standard_strings		VersyPDF_ps_get_standard_strings
#define	ps_unicode_value			VersyPDF_ps_unicode_value
#define	psnames_get_service			VersyPDF_psnames_get_service
#define	ps_parser_done				VersyPDF_ps_parser_done
#define	ps_parser_init				VersyPDF_ps_parser_init
#define	ps_parser_load_field		VersyPDF_ps_parser_load_field
#define	ps_parser_skip_PS_token		VersyPDF_ps_parser_skip_PS_token
#define	ps_parser_skip_spaces		VersyPDF_ps_parser_skip_spaces
#define	ps_parser_to_bytes			VersyPDF_ps_parser_to_bytes
#define	ps_parser_to_coord_array	VersyPDF_ps_parser_to_coord_array
#define	ps_parser_to_fixed			VersyPDF_ps_parser_to_fixed
#define	ps_parser_to_fixed_array	VersyPDF_ps_parser_to_fixed_array
#define	ps_parser_to_int			VersyPDF_ps_parser_to_int
#define	ps_parser_to_token			VersyPDF_ps_parser_to_token
#define	ps_parser_to_token_array	VersyPDF_ps_parser_to_token_array
#define	ps_radix					VersyPDF_ps_radix
#define	ps_table_add				VersyPDF_ps_table_add
#define	ps_table_done				VersyPDF_ps_table_done
#define	ps_table_new				VersyPDF_ps_table_new
#define	ps_table_release			VersyPDF_ps_table_release
#define	ps_tobool					VersyPDF_ps_tobool
#define	ps_tobytes					VersyPDF_ps_tobytes
#define	ps_tocoordarray				VersyPDF_ps_tocoordarray
#define	ps_tofixed					VersyPDF_ps_tofixed
#define	ps_tofixedarray				VersyPDF_ps_tofixedarray
#define	ps_toint					VersyPDF_ps_toint
#define	reallocate_t1_table			VersyPDF_reallocate_t1_table
#define	shift_elements				VersyPDF_shift_elements
#define	skip_comment				VersyPDF_skip_comment
#define	skip_literal_string			VersyPDF_skip_literal_string
#define	skip_spaces					VersyPDF_skip_spaces
#define	skip_string					VersyPDF_skip_string
#define	t1_builder_add_contour		VersyPDF_t1_builder_add_contour
#define	t1_builder_add_point		VersyPDF_t1_builder_add_point
#define	t1_builder_add_point1		VersyPDF_t1_builder_add_point1
#define	t1_builder_check_points		VersyPDF_t1_builder_check_points
#define	t1_builder_close_contour	VersyPDF_t1_builder_close_contour
#define	t1_builder_done				VersyPDF_t1_builder_done
#define	t1_builder_init				VersyPDF_t1_builder_init
#define	t1_builder_start_point		VersyPDF_t1_builder_start_point
#define	t1_decrypt					VersyPDF_t1_decrypt
#define	afm_atoi					VersyPDF_afm_atoi
#define	afm_atoindex				VersyPDF_afm_atoindex
#define	compare_kern_pairs			VersyPDF_compare_kern_pairs
#define	T1_Done_Metrics				VersyPDF_T1_Done_Metrics
#define	T1_Get_Kerning				VersyPDF_T1_Get_Kerning
#define	T1_Read_AFM					VersyPDF_T1_Read_AFM
#define	T1_Read_Metrics				VersyPDF_T1_Read_Metrics
#define	T1_Read_PFM					VersyPDF_T1_Read_PFM
#define	t1_cmap_custom_class_rec	VersyPDF_t1_cmap_custom_class_rec
#define	t1_cmap_expert_class_rec	VersyPDF_t1_cmap_expert_class_rec
#define	t1_cmap_standard_class_rec	VersyPDF_t1_cmap_standard_class_rec
#define	t1_cmap_unicode_class_rec	VersyPDF_t1_cmap_unicode_class_rec
#define	t1_cmap_custom_init			VersyPDF_t1_cmap_custom_init
#define	t1_cmap_custom_done			VersyPDF_t1_cmap_custom_done
#define	t1_cmap_custom_char_index	VersyPDF_t1_cmap_custom_char_index
#define	t1_cmap_custom_char_next	VersyPDF_t1_cmap_custom_char_next
#define	t1_cmap_expert_init			VersyPDF_t1_cmap_expert_init
#define	t1_cmap_std_init			VersyPDF_t1_cmap_std_init
#define	t1_cmap_std_done			VersyPDF_t1_cmap_std_done
#define	t1_cmap_std_char_index		VersyPDF_t1_cmap_std_char_index
#define	t1_cmap_std_char_next		VersyPDF_t1_cmap_std_char_next
#define	t1_cmap_unicode_done		VersyPDF_t1_cmap_unicode_done
#define	t1_cmap_unicode_init		VersyPDF_t1_cmap_unicode_init
#define	t1_cmap_unicode_char_index	VersyPDF_t1_cmap_unicode_char_index
#define	t1_cmap_unicode_char_next	VersyPDF_t1_cmap_unicode_char_next
#define	t1_decoder_done				VersyPDF_t1_decoder_done
#define	t1_decoder_init				VersyPDF_t1_decoder_init
#define	t1_decoder_parse_charstrings	VersyPDF_t1_decoder_parse_charstrings
#define	t1_decoder_parse_glyph		VersyPDF_t1_decoder_parse_glyph
#define	t1_lookup_glyph_by_stdcharcode	VersyPDF_t1_lookup_glyph_by_stdcharcode
#define	t1operator_seac				VersyPDF_t1operator_seac
#define	Get_Interface				VersyPDF_Get_Interface
#define	t1_get_glyph_name			VersyPDF_t1_get_glyph_name
#define	t1_get_name_index			VersyPDF_t1_get_name_index
#define	t1_get_ps_name				VersyPDF_t1_get_ps_name
#define	t1_ps_get_font_info			VersyPDF_t1_ps_get_font_info
#define	t1_ps_get_font_private		VersyPDF_t1_ps_get_font_private
#define	t1_ps_has_glyph_names		VersyPDF_t1_ps_has_glyph_names
#define	T1_Compute_Max_Advance		VersyPDF_T1_Compute_Max_Advance
#define	T1_Load_Glyph				VersyPDF_T1_Load_Glyph
#define	T1_Parse_Glyph				VersyPDF_T1_Parse_Glyph
#define	T1_Parse_Glyph_And_Get_Char_String VersyPDF_T1_Parse_Glyph_And_Get_Char_String
#define	is_space					VersyPDF_is_space
#define	parse_charstrings			VersyPDF_parse_charstrings
#define	parse_dict					VersyPDF_parse_dict
#define	parse_encoding				VersyPDF_parse_encoding
#define	parse_fd_array				VersyPDF_parse_fd_array
#define	parse_blend_axis_types		VersyPDF_parse_blend_axis_types
#define	parse_blend_design_positions	VersyPDF_parse_blend_design_positions
#define	parse_blend_design_map		VersyPDF_parse_blend_design_map
#define	parse_blend_axis_types		VersyPDF_parse_blend_axis_types
#define	parse_weight_vector			VersyPDF_parse_weight_vector
#define	parse_subrs					VersyPDF_parse_subrs
#define	t1_done_loader				VersyPDF_t1_done_loader
#define	t1_init_loader				VersyPDF_t1_init_loader
#define	t1_load_keyword				VersyPDF_t1_load_keyword
#define	T1_Open_Face				VersyPDF_T1_Open_Face
#define	T1_Driver_Init				VersyPDF_T1_Driver_Init
#define	T1_Driver_Done				VersyPDF_T1_Driver_Done
#define	T1_Face_Done				VersyPDF_T1_Face_Done
#define	T1_Face_Init				VersyPDF_T1_Face_Init
#define	T1_GlyphSlot_Done			VersyPDF_T1_GlyphSlot_Done
#define	T1_GlyphSlot_Init			VersyPDF_T1_GlyphSlot_Init
#define	T1_Size_Get_Globals_Funcs	VersyPDF_T1_Size_Get_Globals_Funcs
#define	T1_Size_Init				VersyPDF_T1_Size_Init
#define	T1_Size_Done				VersyPDF_T1_Size_Done
#define	T1_Size_Reset				VersyPDF_T1_Size_Reset
#define	check_type1_format			VersyPDF_check_type1_format
#define	read_pfb_tag				VersyPDF_read_pfb_tag
#define	T1_Finalize_Parser			VersyPDF_T1_Finalize_Parser
#define	T1_Get_Private_Dict			VersyPDF_T1_Get_Private_Dict
#define	T1_New_Parser				VersyPDF_T1_New_Parser

#define   cid_slot_load_glyph   VersyPDF_cid_slot_load_glyph
#define   t1cid_driver_class   VersyPDF_t1cid_driver_class
#define   FT_Outline_Get_BBox   VersyPDF_FT_Outline_Get_BBox
#define   FT_Get_BDF_Property   VersyPDF_FT_Get_BDF_Property
#define   _debug_mem_dummy   VersyPDF__debug_mem_dummy
#define   FT_GlyphLoader_CreateExtra   VersyPDF_FT_GlyphLoader_CreateExtra
#define   FT_GlyphLoader_CheckPoints   VersyPDF_FT_GlyphLoader_CheckPoints
#define   FT_GlyphLoader_CheckSubGlyphs   VersyPDF_FT_GlyphLoader_CheckSubGlyphs
#define   FT_GlyphLoader_Prepare   VersyPDF_FT_GlyphLoader_Prepare
#define   FT_GlyphLoader_Add   VersyPDF_FT_GlyphLoader_Add
#define   FT_GlyphLoader_CopyPoints   VersyPDF_FT_GlyphLoader_CopyPoints
#define   ft_outline_glyph_class   VersyPDF_ft_outline_glyph_class
#define   FT_Set_MM_Design_Coordinates   VersyPDF_FT_Set_MM_Design_Coordinates
#define   FT_Set_Var_Design_Coordinates   VersyPDF_FT_Set_Var_Design_Coordinates
#define   FT_Set_MM_Blend_Coordinates   VersyPDF_FT_Set_MM_Blend_Coordinates
#define   FT_Set_Var_Blend_Coordinates   VersyPDF_FT_Set_Var_Blend_Coordinates
#define   FT_Get_Charmap_Index   VersyPDF_FT_Get_Charmap_Index
#define   FT_Get_Sfnt_Table   VersyPDF_FT_Get_Sfnt_Table
#define   ps_table_funcs   VersyPDF_ps_table_funcs
#define   ps_parser_funcs   VersyPDF_ps_parser_funcs
#define   t1_builder_funcs   VersyPDF_t1_builder_funcs
#define   t1_decoder_funcs   VersyPDF_t1_decoder_funcs
#define   t1_cmap_classes   VersyPDF_t1_cmap_classes
#define   psaux_module_class   VersyPDF_psaux_module_class
#define   pshinter_module_class   VersyPDF_pshinter_module_class
#define   psnames_module_class   VersyPDF_psnames_module_class
#define   ps_parser_load_field_table   VersyPDF_ps_parser_load_field_table
#define   t1_driver_class   VersyPDF_t1_driver_class



#endif //_VSFREETYPE_H
